### ISSUE TITLE
Globaler Modus / Cannot find module '/var/lib/homebridge/lib/user'

### ISSUE THREAD

**Issue by Marpolli** [ioBroker/ioBroker.ham#117]
Hallo Zusammen,

ich betreibe schon länge eine separate Homebridge neben dem ioBroker und wollte heute die Gelegenheit nutzten euren Adapter zu testen sowie die separate Instanz herunterzufahren. Leider habe ich bisher es nicht geschafft die Instanz im ioBroker zu starten und erhalte nur folgende Fehlermeldungen:

`
ham.0 | 2021-04-01 16:37:44.607 | warn | (1622) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
ham.0 | 2021-04-01 16:37:44.607 | info | (1622) terminating
ham.0 | 2021-04-01 16:37:44.606 | info | (1622) cleaned everything up...
ham.0 | 2021-04-01 16:37:44.559 | error | (1622) Exception-Code: MODULE_NOT_FOUND: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/i
ham.0 | 2021-04-01 16:37:44.559 | error | (1622) Error: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/iobroker.ham/main.js at
ham.0 | 2021-04-01 16:37:44.558 | error | (1622) unhandled promise rejection: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/iobrok
ham.0 | 2021-04-01 16:37:44.558 | error | (1622) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ham.0 | 2021-04-01 16:37:44.545 | info | (1622) No additional Libraries to install ...
ham.0 | 2021-04-01 16:37:44.531 | info | (1622) starting. Version 4.0.1 in /opt/iobroker/node_modules/iobroker.ham, node: v14.16.0, js-controller: 3.2.16
ham.0 | 2021-04-01 16:37:13.087 | warn | (1599) Terminated (UNCAUGHT_EXCEPTION): Without reason
ham.0 | 2021-04-01 16:37:13.086 | info | (1599) terminating
ham.0 | 2021-04-01 16:37:13.086 | info | (1599) cleaned everything up...
ham.0 | 2021-04-01 16:37:13.039 | error | - /opt/iobroker/node_modules/iobroker.ham/main.js
ham.0 | 2021-04-01 16:37:13.039 | error | - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js
ham.0 | 2021-04-01 16:37:13.039 | error | Require stack:
ham.0 | 2021-04-01 16:37:13.039 | error | (1599) Exception-Code: MODULE_NOT_FOUND: Cannot find module '/var/lib/homebridge/lib/user'
ham.0 | 2021-04-01 16:37:13.039 | error | at checkLocalMode (/opt/iobroker/node_modules/iobroker.ham/main.js:400:25)
ham.0 | 2021-04-01 16:37:13.039 | error | at /opt/iobroker/node_modules/iobroker.ham/main.js:203:13
ham.0 | 2021-04-01 16:37:13.039 | error | at installAllLibraries (/opt/iobroker/node_modules/iobroker.ham/main.js:381:21)
ham.0 | 2021-04-01 16:37:13.039 | error | at /opt/iobroker/node_modules/iobroker.ham/main.js:217:39
ham.0 | 2021-04-01 16:37:13.039 | error | at Object.init (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:64:12)
ham.0 | 2021-04-01 16:37:13.039 | error | at require (internal/modules/cjs/helpers.js:88:18)
ham.0 | 2021-04-01 16:37:13.039 | error | at Module.require (internal/modules/cjs/loader.js:952:19)
ham.0 | 2021-04-01 16:37:13.039 | error | at Function.Module._load (/opt/iobroker/node_modules/mock-require/index.js:30:22)
ham.0 | 2021-04-01 16:37:13.039 | error | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ham.0 | 2021-04-01 16:37:13.039 | error | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ham.0 | 2021-04-01 16:37:13.039 | error | - /opt/iobroker/node_modules/iobroker.ham/main.js
ham.0 | 2021-04-01 16:37:13.039 | error | - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js
ham.0 | 2021-04-01 16:37:13.039 | error | Require stack:
ham.0 | 2021-04-01 16:37:13.039 | error | (1599) Error: Cannot find module '/var/lib/homebridge/lib/user'
ham.0 | 2021-04-01 16:37:13.038 | error | - /opt/iobroker/node_modules/iobroker.ham/main.js
ham.0 | 2021-04-01 16:37:13.038 | error | - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js
ham.0 | 2021-04-01 16:37:13.038 | error | Require stack:
ham.0 | 2021-04-01 16:37:13.038 | error | (1599) unhandled promise rejection: Cannot find module '/var/lib/homebridge/lib/user'
ham.0 | 2021-04-01 16:37:13.038 | error | (1599) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ham.0 | 2021-04-01 16:37:13.022 | info | (1599) No additional Libraries to install ...
ham.0 | 2021-04-01 16:37:13.006 | info | (1599) starting. Version 4.0.1 in /opt/iobroker/node_modules/iobroker.ham, node: v14.16.0, js-controller: 3.2.16
`

Neben den internen Ausgaben ist besonders "(1599) Error: Cannot find module '/var/lib/homebridge/lib/user'" auffällig. Fehlt mir hier ein Modul damit der Adapter starten kann?

Mfg Marpolli

**Comment by Apollon77** [comment]
Welche Verison vom homebride ist global installiert? Der 4.x Adapter braucht ein homebridge 1.3.x ... das  muss passen. Daher war es beim Adapter auch ein Major Version increase was "breakign" anzeigt

**Comment by Marpolli** [comment]
Es ist eine frisch installierte Instanz. Die Version ist v1.3.4 und den 4.x Adapter habe ich nur installiert weil der Fehler vorher schon da war in der stable. Ich wollte ausschließen, dass ich eine zu neue Version der HB habe.

**Comment by Marpolli** [comment]
Habe den Fehler gefunden indem ich mich ein wenig im Code herumgeschaut habe und entsprechend "Rückwärts" langsam vorgearbeitet habe. Es hat sich herausgestellt, dass die "default"-Werte in den Einstellungen des HAM-Adapters nicht nur falsch sondern auch sehr irreführend sind.

![snip](https://user-images.githubusercontent.com/18574846/113351433-2b13bf00-933b-11eb-8bd3-172c0140088d.PNG)

In meinem Fall stand dort per Default bei 1. "/var/lib/homebridge" und bei 2. "/var/lib/homebridge/config.json". Durch die Anpassung der Pfade auf den richtigen Wert startet der Adapter nun und scheinbar laufen auch alle Plugins reibungslos. Die Beschreibung (und der Default) sollten hier angepasst werden... :D

**Comment by Apollon77** [comment]
Die Pfade hängen sehr stark davon ab wie homebridge installiert wurde ... wie hast Du es denn installiert?

**Comment by Marpolli** [comment]
Ganz normal nach Vorgabe der Wiki: 
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

Das heißt also mittels NPM:
`apt-get install -y nodejs gcc g++ make python net-tools
npm install -g --unsafe-perm homebridge homebridge-config-ui-x
hb-service install --user homebridge`
