### ISSUE TITLE
Global option with Docker Homebridge on Synology?

### ISSUE THREAD

**Issue by henkhb** [ioBroker/ioBroker.ham#13]

**Comment by Apollon77** [comment]
See Forum, I do not see this as a topic for the adapter.

**Comment by LuxBibi** [comment]
Hallo @henkhb .

Alter Thread, jedoch versuch ich meine Chance, da ich bis dato die Tage nicht viel hierzu gefunden habe.

Hast Du zu dieser Thematik je eine Lösung gefunden? Ich habe docker/ioBroker auf Synology, und separate Homebridge Instanz, auch mittels Docker auf gleicher Synology. Beide funktionieren perfekt! Möchte jetzt meine Docker/Homebridge mittels ioBroker.ham in mein Docker/ioBroker integrieren ... Hast du dies hinbekommen? Dank im Voraus
