### ISSUE TITLE
homebridge-tydom funktioniert nicht korrekt mit ioBroker.ham

### ISSUE THREAD

**Issue by mac89muc** [ioBroker/ioBroker.ham#146]
Hallo zusammen,

ich nutze zur Steuerung meiner Thermostate den  [homebridge-tydom Adapter](https://github.com/mgcrea/homebridge-tydom#readme) für Geräte von [Delta Dore](https://www.deltadore.de)
Das funktioniert über die reguläre Homebridge installation auch soweit ohne Probleme.

Es wird für jedes Heizungsthermostat über die Homebridge in HomeKit ein Thermostat erzeugt mit Current & Target State - aktueller Temperatur und Zieltemperatur, dazu dann noch eine Abwesehenheits Switch.

Möchte ich das Plugin allerdings direkt über dan ham Adapter in iobroker (wrapper Modus) laufen lassen, habe ich Probleme. Er erzeugt mir zwar die Datenpunkte - also Current & Target State, aktuelle sowie Zieltemperatur und den Abwesenheitsmodus, allerdings aktualisieren sich die Datenpunkte mit Temperatur und Current/Target State nicht korrekt und Änderungen in den Datenpunkten werden nicht weitergegeben an die Heizungsthermostate.

Ich gebe bei den Adaptereinstellungen bei den zusätzlichen npm Modulen den homebridge-tydom adapter mit an und in der Konfigurationsdatei die Angaben analog der normalen config.json bei der "normalen" Homebridge installation.

Habe die ursprünglich Homebridge installation auf meinem Rechner komplett deinstalliert und das ursprüngliche homebridge-tydom Plugin dort auch um Komplikationen zu vermeiden (sudo npm list -g --depth=0) zeigt mir keine Homebridge und keine Homebridge Adapter mehr auf meinem System) - somit sollte also eigentlich nur noch die Installation über den ham Adapter laufen.

Habt ihr einen Tipp für mich, woran das liegen könnte?

Platform: OSX
os: darwin
Architecture: x64
CPUs: 2
Speed: 2000 MHz
Model: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
RAM: 4 GB 
System uptime: 3 T. 09:19:09
Node.js: v14.15.4
NPM: 6.14.10
Disk size: 297.3 GiB
Disk free: 99.3 GiB
adapters count: 345
Uptime: 3 T. 09:16:51
Active instances: 17

**Comment by Apollon77** [comment]
Bitte ham Adapter auf Loglevel debug stellen und log posten vom Start und auch dann von einer Steueraktion.
Bitte Log aus dem Logfile auf Platte /opt/iobroker/log nehmen

**Comment by mac89muc** [comment]
Danke für die schnelle Rückinfo - soll ich Dir das Logfile hier mit copy&paste reinsetzen, oder hättest Du die Datei gerne per PN?

**Comment by mac89muc** [comment]
Habs Dir jetzt mal hier mit angehangen - Zeitpunkt ab der ham Installation, hoffe Du kannst was daraus ableiten.
Nutze den iobroker ja eigentlich über osx, habe aber zur Kontrolle auf dem macmini nochmal über Virtualbox eine komplett neue Installation von ubuntu mit iobroker gemacht um auszuschließen, dass irgendwelche alten Installationsschnipsel das Problem verursachen. 
Aber auch hier bei der frischen Installation ohne vorherige Homebridge Installation etc. das gleiche Problem - anfänglich zieht er sich die korrekten Werte, danach ist allerdings schluss und es werden keine Werte die in den Datenpunkten geändert werden an die Thermostate übermittelt und auch die aktuellen Werte der Thermostate werden nicht mehr korrekt in den Datenpunkten abgelegt.

Gruß

[iobroker.2021-05-28 .log](https://github.com/ioBroker/ioBroker.ham/files/6564543/iobroker.2021-05-28.log)

**Comment by Apollon77** [comment]
Hi,

Bitte Stelle Adapter mal in den Debug Logmodus! Admin - instanzen - expertemodus ... Logstufe "debug". und dann bitte neues Log.

Generell sehe ich das du beim Bad Thermostatdie Temperatur auf 22 gesetzt hast und das wurde auch vom Plugin bestätigt.

ANsonsten scheinst Du irgendwier DNS/Netwerk Probleme zu haben (EAGAIN) und Namensauflösung bei npm ... und Dein RAM ist bissl knapp ... und ich tippe das deswegen dein system zwischendrin mal komplett abgekachelt ist ... also bitte mal das zeurst fixen!

**Comment by mac89muc** [comment]
Das RAM Problem etc lag wohl an der Virtuellen Ubuntu Installation, die ja nur auf einen Teil des RAMs zugriff hatte.

Hab nochmal ein neues Log (Debug beim ham Adapter) gezogen auf dem Mac mini und der osx iobroker Installation mit dem ham Adapter im lokalen Modus.
Die Homebridge lässt sich wieder ganz normal in Homekit einbinden und die gefundenen Thermostate werden anschließend automatisch inkl. des dazugehörenden Abwesenheits-Switches zur Einbindung in Homekit angeboten und können den jeweiligen Räumen zugeordnet werden.

Soweit so gut - unter osx ist das Log übrigens in folgendem Ordner zu finden - /usr/local/iobroker/log
Habe mal alles andere aus dem Log geschmissen, was andere Adapter betrifft.

[iobroker.2021-06-11.log](https://github.com/ioBroker/ioBroker.ham/files/6637422/iobroker.2021-06-11.log)


Mir sind zwei Sachen aufgefallen:

Zum einen werden wie schon oben mal erwähnt die Änderungen die über die Home App und die dort angelegten Thermostate gemacht werden bisher ohne Probleme an die physischen Thermostate weitergegeben und die Temperatur etc wird korrekt eingestellt. Auch wenn ich Änderungen über die offizielle DeltaDore App machen, werden diese Änderungen korrekt an die angezeigten Thermostate in Homekit weitergereicht. Das heißt, Änderungen in Homekit werden korrekt an die Heizungen weitergereicht und Änderungen direkt an den Heizungen bzw. über die offizielle DeltaDore App werden auch korrekt von Homekit übernommen bzw angezeigt.

Was allerdings nicht funktioniert ist die Aktualisierung der Datenpunkte unter den ham Objekten.
Weder wenn ich die Temperatur oder Abwesenheitsmodus in Homekit ändere, noch wenn ich die Werte in der offiziellen DeltaDore App ändere. Am Anfang beim Start des ham Adapters zieht er sich meist die korrekten Werte aber dann aktualisiert er eben nicht mehr. Also werden die Änderungen aktuell an den Datenpunkten vorbei gereicht - in die eine, wie auch die andere Richtung.

Auch wenn ich in den Objekten die Datenpunkte direkt ändere und z.B. die Temperatur ändere, wird die Änderung weder an das Homekit Thermostat übermittelt noch an die Heizung bzw. auch nicht von der DeltaDore App angezeigt.

Also scheint es ein Problem beim schreiben oder ändern der Datenpunkte zu geben..

Das zweite was mir aufgefallen ist, Teilweise steht im Log eine Meldung ACK not Set - keine Ahnung, ob das nur ein Hinweis ist, bis die Änderung bestätigt wird und dann greift, oder das u.U. ein Problem ist.

Gruß

**Comment by EyesOnly1** [comment]
Hallo Zusammen. Ich habe ebenfalls ein aktualisierungs Problem mit den Datenpunkten aber mit dem homebridge-smartthings Adapter. Bei Start von ham werden auch alle Datenpunkte erzeugt und auch mit den aktuellen Werten gesetzt. Eine erneute Aktualisierung von Werten welche in Smartthings geändert wurden finden in den Datenpunkten nicht statt. Macht man einen Restart der ham Instanz werden die Werte auch wieder aktuell gezogen aber nicht erneut aktualisiert.

**Comment by Apollon77** [comment]
Wa sist denn als Polling Intervall eingestellt? EInige Plugins senden keine aktuellen Werte sondern wollen immer neu abgefragt werden ... daher polling Interval ... Sonst bitte ein vollen debug log, was aber in jedem Fall so einen polling vorgang enthalten solölte (weil initial wird nichts anders getan als beim polling und wenn das tut ... vllt nicht lang  genug gewartet ??

**Comment by mac89muc** [comment]
Danke für Deine Rückmeldung.

Polling habe ich verschiedene Werte versucht allerdings ohne Erfolg - Problem bleibt bestehen..

Vielleicht mal für mich zur Erklärung. 
Die Werte die über die Homebridge im lokalen Modus an HomeKit weitergereicht werden stimmen, nur eben die Datenpunkte in ioBroker nicht..
Ich bin bisher davon ausgegangen, dass die Datenpunkte im ham Adapter über die lokale Bridge sozusagen gespiegelt bzw. an HomeKit weitergereicht werden, dies ist wohl nicht so, korrekt?

Dann ansonsten müssten die Daten die mir in HomeKit über die Geräte die per lokaler Bridge angezeigt werden in HK ja mit den Daten in den ioBroker Datenpunkten des ham Adapters übereinstimmen.

Wenn ich also Werte im Thermostat in HK abändere z.B. über HomeKit die Temperatur Bad auf 22° einstelle, werden diese korrekt an das Tydom Gateway weitergereicht und das Heizthermostat Bad stellt sich auf 22° ein - in den ham Datenpunkten Bad werden mir allerdings nicht die 22° angezeigt sondern z.B. 10°

Ebenso funktioniert das Ändern der Temperatur z.B. über die offizielle Tydom App - stelle ich die Bad Temperatur z.B. auf 25° in der Tydom App wird die Temperatur auch in HomeKit im entsprechenden Thermostat Bad übernommen/angezeigt, aber wieder nicht in den Datenpunkten des ham Adapters.

Also sind die ham Datenpunkte nicht gekoppelt an die Bridge Werte die in HK angezeigt werden, korrekt?

Dementsprechend liest der ham Adapter die Werte nicht korrekt weder in die eine Richtung von HomeKit nach Tydom Gateway, noch in die andere Richtung vom Tydom Gateway nach HomeKit.

Gruß

**Comment by Apollon77** [comment]
Bitte Log mit aktiviertem Debug Log machen vpm Adapterstart und entsprechenden Aktiopnen "in alle Richtungen" und jeweils notieren wann das zeitlich war und pausen lassen das ich später Aktionen und Log zeitlich zuordnen kann. Wenn nötig Debug Log per E-Mail an iobroker@fischer-ka.de senden unter verweis auf dieses Issue (inkl. Issue Link).
Bitte Log von der Platte unter /opt/iobroker/log/... nehmen und nicht aus Admin

**Comment by mac89muc** [comment]
Hier das neue Log von heute direkt von der Platte ab Neustart ham Adapter um 17 Uhr.
Kurzum wie oben beschreiben funktioniert die Steuerung von Homekit über die dort angezeigten Thermostate und auch die Steuerung direkt über die offizielle Tydom App. Ändere ich Werte in eine der beiden Apps werden diese von der anderen und letztendlich auch von Thermostat übernommen - allerdings nicht in den Objekten im ham Adapter.

Auch Änderungen die ich über den ham Adapter bzw. die Objekte durchführe werden weder von der Homekit App noch in der Tydom App übernommen bzw. angezeigt - noch wird das Thermostat mit den Eingaben über die ham Objekte angesprochen.

Folgende 3 Dinge sind mir beispielhaft im Log aufgefallen, keine Ahnung ob das irgendwelche Auswirkungen hat

2021-08-06 17:01:53.050  - [33mwarn[39m: ham.0 (25063) Error while getting current value: -70405
oder
2021-08-06 17:05:33.462  - [34mdebug[39m: ham.0 (25578) [8/6/2021, 5:05:33 PM] [homebridge-tydom] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
oder
2021-08-06 17:32:38.711  - [34mdebug[39m: ham.0 (25578) [8/6/2021, 5:32:38 PM] [homebridge-tydom] This plugin slows down Homebridge. The read handler for the characteristic 'Current Heating Cooling State' was slow to respond! See https://git.io/JtMGR for more info.

Die Eingaben über die unterschiedlichen Eingabemöglichkeiten (Homekit, Tydom App, ioBroker Objekte) die ich zu den jeweiligen Uhrzeiten gemacht habe mit den entsprechenden Ergebnissen wo diese übernommen wurden findest Du ebenso im Anhang.

Danke & Gruß

[iobroker.2021-08-06 ham_tydom.log](https://github.com/ioBroker/ioBroker.ham/files/6946892/iobroker.2021-08-06.ham_tydom.log)
<img width="734" alt="zeiten" src="https://user-images.githubusercontent.com/69312437/128545177-b02b2618-2239-4c4e-bdb3-b8f9d47bccf6.png">

**Comment by Apollon77** [comment]
Naja wegen den Warnungen würde ich eher mal im Repo des Plgins was schreiben oder schauen ob es eine neue Version des Plugins gibt?

**Comment by mac89muc** [comment]
Hab gerade nochmal Neustart mit gesetztem Haken bei "beim Start Plugins von NPM aktualisieren" durchgeführt. Ist aber nicht die Ursache für das hauptsächliche Problem. Hoffe Du kannst mit dem Log was anfangen und es findet sich die Ursache.

Gruß

**Comment by mac89muc** [comment]
@Apollon77 hattest du schon Zeit Dir das Logo anzusehen?

Gruß

**Comment by Apollon77** [comment]
sorry nope. war im Urlaub :-)

**Comment by mac89muc** [comment]
@Apollon77 wollte mal nach dem aktuellen Status hierzu fragen. Brauchst Du noch Infos von mir? 

Gruß

**Comment by mac89muc** [comment]
Hallo @Apollon77, zwischendurch wieder etwas Zeit vergangen. Gibt es hierzu Neuigkeiten, brauchst du noch Infos? Rückmeldung wäre nett. Gruß

**Comment by Apollon77** [comment]
Nein kene offensichtlichen Erkenntnisse ... muss in den Code des Plugins schauen ob da was komisches gemacht wird, sorry.

**Comment by Apollon77** [comment]
Ok, on GitHub we have a new update available. This is now compatible to homebridge 1.4.1 and adds some more logs.

So if you use global mode please update global homebridge to 1.4.1 too before updating the adapter. Please also check and pot update zthe used plugins (or set the "Update" flag in adapter-config.
Please set the loglevel of the instance to debug and cpost the log with tries - if nothing is in please set loglwevel to silly and post log together (again with infos when you did what with times and what happened on the device so that I can maybe correlate it to the log).

**Comment by Apollon77** [comment]
Please use 5.0.1 just released this morning andprovide new logs if still relevant

**Comment by Apollon77** [comment]
Ok, please try newest 5.2.0 Alpha Github version, see https://forum.iobroker.net/topic/57891/test-adapter-ham-5-2-0-github

**Comment by mac89muc** [comment]
Meanwhile I have had switched to different heaters. Thanks
