### ISSUE TITLE
Globaler Modus Homebridge in Docker

### ISSUE THREAD

**Issue by ChaotenKurt** [ioBroker/ioBroker.ham#165]
Hallo,

Vielleicht kann mir ja jemand weiter helfen. Ich habe iobroker sowie Homebrigde in Docker auf einer Synology zu laufen.  In Docker habe ich den Ordner von meiner bestehenden Homebridge installation in iobroker freigegeben. Was muss ich jetzt in iobroker unter Global Homebridge Path und Global Homebridge Config Directory Path eingeben?

In Docker lautet der Mount-Pfad : /opt/homebridge

Vielen Dank im Voraus

**Comment by Apollon77** [comment]
Beides ist im gleichen Container? Dann musst Du den Pfad ermitteln wie es auch in der Readme heisst. Ich verstehe die Frage gerade nicht ganz

**Comment by ChaotenKurt** [comment]
Sorry dass ich mich anscheinend zu ungenau ausgedrückt habe. Hoffe man kann es jetzt besser nachvollziehen.

IOBroker und Homebridge laufen bei mir jeweils in einem separaten Docker Container auf meiner Synology. Auf der Synology habe ich einen Ordner für Docker, wo Wiederrum Unterordner für die jeweiligen Docker Container enthalten sind (ein Ordner IOBroker, ein Ordner Homebridge)

Alle Daten werden dort in diesen Ordner gespeichert, sodass ich die Docker Container jederzeit aktualisieren kann, ohne die Daten zu verlieren.

Jetzt habe ich folgendes getan, und habe meinem IOBroker Container einfach zusätzlich das Recht zugeteilt, dass er im Homebridge Ordner Lesen und Schreiben kann.

Nur wenn ich diesen Pfad in IOBroker eingebe, findet er dennoch nicht die Daten um sich zu verbinden.

Ich hoffe, ich konnte mich jetzt ausführlicher ausdrücken.

![Bildschirmfoto 2021-06-08 um 08 35 53](https://user-images.githubusercontent.com/80848243/121135410-c0986700-c834-11eb-9abe-5da0626c5e53.png)
![Bildschirmfoto 2021-06-08 um 08 36 40](https://user-images.githubusercontent.com/80848243/121135416-c1c99400-c834-11eb-98f9-797a41dcabd2.png)

![Bildschirmfoto 2021-06-08 um 08 33 40](https://user-images.githubusercontent.com/80848243/121135335-b1191e00-c834-11eb-82fd-e9120500d9d3.png)

**Comment by Apollon77** [comment]
> IOBroker und Homebridge laufen bei mir jeweils in einem separaten Docker Container auf meiner Synology

Das macht mit dem HAM Adapter Ansatz keinen sinn mehr ... ein Container oder nicht Ham Adapter. Der Ham adaoter startet doch homebridge ...

**Comment by LuxBibi** [comment]
Hallo @ChaotenKurt ,
Hallo @Apollon77 ,
Bin bereits etwas länger genau die gleiche Lösung am suchen ;-)

@Apollon77: Geb dir grundsätzlich recht ;-). Jedoch gibt es verschiedene "Bedürfnisse", wo dies einen Nutzen bringt. Meines Erachtens, alles was nicht in HomeKit, also im HAM-Adapter verfügbar ist, jedoch mittels HomeBridge integrierbar ist? (Oder hab ich hier noch was nicht ganz verstanden? Lerne gerne dazu um meine Installation gemäss KISS-Prinzip (Keep it Simple and Stupid ;-) so einfach und stabil wie möglich zu halten) In meinem Fall ist z.Bsp. ein tedees-Schloss mittels HomeBridge "integriert". Funktioniert seit Wochen perfekt/schnell und sehr stabil. (Danke HomeBridge/Docker auf meiner Synology) Ich weiss, dass tedee an der HomeKit-Integration arbeitet .. aber dies dauert .... und kommt ggfls. nicht so schnell ... 

@ChaotenKurt : Hast du mittlerweile eine Lösung gefunden, wie du die "Accesories" aus HomeBridge in IoBroker (DPT's) lesen/schreiben kannst?

Danke an alle für jegliche Info/Hilfe ;-)

Luc aus Luxemburg.

**Comment by ChaotenKurt** [comment]
@LuxBibi 

leider nein, ich hatte dann Home Assistant in Docker ausprobiert und muss sagen, dass ich dort jetzt geblieben bin. Homebridge nutze ich nur noch für Philips Hue, da ich dort die Möglichkeit von Adaptive Light habe, welches in Home Assistent noch nicht unterstützt wird (bzw. ich nicht gesehen habe).

**Comment by LuxBibi** [comment]
Danke @Apollon77 ,
Hatte dein Feedback verpasst .... Weswegen die sehr späte Rückmeldung ... Bleibe interessiert, so wie sich hier etwas Neues tut ... da ich gerne die "HomeKit-Objekte" im ioBroker nutzen möchte ... 

Schöne Feiertage, und bis nächstes Jahr ... 
Luc

**Comment by uwe72** [comment]
Habe iobroker als auch Homebridge jeweils im docker laufen. In Iobroker habe ich den Ham Adapter installiert. Kriege ich den mit der Homebridge Installation (mittlerweilen) verbunden?

**Comment by Apollon77** [comment]
In meiner Welt ist die Frage einfach: HomeKit basiert auf UDP/MDNS für das Discovery ... also ... Docker im Host Modus oder mit MacVLAN sollte tun ... sonst eher schwierig weil UDP nicht geroutet wird .....  wäre mein Wissensstand.

**Comment by uwe72** [comment]
Homebridge läuft bei mir extern. Die Frage die ich mir stelle ist, was ich hier dann einstelle im HAM-Adapter, so dass ich auf die separate Homebridge-Installation zugreifen kann und Datenpunkte erhalte?

![image](https://github.com/ioBroker/ioBroker.ham/assets/61848539/23234435-0172-48ae-b7f4-f2f8c158c7c8)

**Comment by Apollon77** [comment]
Das funktioniert nicht. weil Homebridge soetwas nicht anbietet. Entweder alles zusammen (globaler modus heisst das ein Homebridge auf der gleichen maschiene wie ioBroker angezapft wird - indem aber ioBorker dieses homebridge dann startet und sich einklingt.
