### ISSUE TITLE
homebridge-platform-maxcube

### ISSUE THREAD

**Issue by skatehouse** [ioBroker/ioBroker.ham#166]
homebridge-platform-maxcube

is startet correctly in ioBroker (hb global), but: 
if startet MaxLink state is false 
Link Button has to be true on startup for discovery of accessoires (thermostats)
In this case nothing besides the Max Cube is discovered.
`

ham.0 | 2021-06-08 00:14:30.951 | info | (18622) updateChannel Max!-Link.Max!-Link: name = Max! Link
-- | -- | -- | --
ham.0 | 2021-06-08 00:14:30.949 | info | (18622) updateState Max!-Link.Accessory-Information.Product-Data: value  = null /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Product  Data","unit":""}
ham.0 | 2021-06-08 00:14:30.947 | info | (18622) updateState Max!-Link.Accessory-Information.Software-Revision:  value =  /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Software  Revision","unit":""}
ham.0 | 2021-06-08 00:14:30.945 | info | (18622) updateState Max!-Link.Accessory-Information.Hardware-Revision:  value =  /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Hardware  Revision","unit":""}
ham.0 | 2021-06-08 00:14:30.943 | info | (18622) updateState Max!-Link.Accessory-Information.Configured-Name:  value =  /common=  {"type":"string","read":true,"write":true,"role":"text","name":"Configured  Name","unit":""}
ham.0 | 2021-06-08 00:14:30.941 | info | (18622) updateState  Max!-Link.Accessory-Information.App-Matching-Identifier: value = null  /common=  {"type":"string","read":true,"write":false,"role":"text","name":"App  Matching Identifier","unit":""}
ham.0 | 2021-06-08 00:14:30.939 | info | (18622) updateState Max!-Link.Accessory-Information.Accessory-Flags:  value = 0 /common=  {"type":"number","min":0,"max":4294967295,"read":true,"write":false,"role":"value","name":"Accessory  Flags","un
ham.0 | 2021-06-08 00:14:30.937 | info | (18622) updateState Max!-Link.Accessory-Information.Firmware-Revision:  value = 2.0.13 /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Firmware  Revision","unit":""}
ham.0 | 2021-06-08 00:14:30.936 | info | (18622) updateState Max!-Link.Accessory-Information.Serial-Number:  value = Default-SerialNumber /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Serial  Number","unit":""}
ham.0 | 2021-06-08 00:14:30.934 | info | (18622) updateState Max!-Link.Accessory-Information.Name: value = Max!  Link /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-06-08 00:14:30.933 | info | (18622) updateState Max!-Link.Accessory-Information.Model: value = Max!  Cube /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Model","unit":""}
ham.0 | 2021-06-08 00:14:30.931 | info | (18622) updateState Max!-Link.Accessory-Information.Manufacturer: value  = EQ-3 /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Manufacturer","unit":""}
ham.0 | 2021-06-08 00:14:30.928 | info | (18622) updateState Max!-Link.Accessory-Information.Identify: value =  false /common=  {"type":"boolean","read":false,"write":true,"role":"button","name":"Identify","unit":""}
ham.0 | 2021-06-08 00:14:30.925 | info | (18622) updateChannel Max!-Link.Accessory-Information: name =
h

`

**Comment by Apollon77** [comment]
Sorry, what you mean?
I do not get it. Also while flying over the plugin readme I did not see anything about a maxLink ? The cutted log also does not help.

And PS: Why the maxcube adapter is not working?

**Comment by Apollon77** [comment]
What I see in the logs is that when started via ioBroker then there seem to be timrout issues.

I also wonderabout the logfile because when started bia ibroker the log should be from iobroker log and not "homebridge style" ... you know that for global mode the ham adapter will start homebridge?! So you need to turn off the homebridge instance and start ham adapter to get it started

**Comment by skatehouse** [comment]
Both files are copied from syslog.
The timeout occurs because the cube can‘t establish a connection due to max link accessory off at startup via iobroker.

1st log is deactivated hb process startet via module ham.
2nd is homebridge startet normally as a stand-alone thing.

If you tell me your needs to reproduce, I will manage to give you more information. So you need the logfile of iobroker when starting ham?

**Comment by skatehouse** [comment]
Can be closed. Sorry for inconvenience. 
/var/homebridge/persist had a file for which I had not changed the group to iobroker. 

When coming from HB its difficult to understand, that iobroker runs it as user iobroker. If any old files exist in /var/homebridge/persist or accessories the instance will start, but it crashes when creating accessories. Therefore some acc. have been there and max link was closed.
Please write to docu under 
`IMPORTANT: ioBroker runs as user "iobroker", but homebridge normally as root or homebridge user (depending on how you installed it). You need to make sure that the homebride "persistance" folder can be accessed by the ioBroker user, else you will see errors that the file can not be saved (which can crash the adapter!)´

1. stop old hb instance
2. delete folders persist in accessories
3. give group iobroker access to /var/homebridge 
4. change group write settings for group in /var/homebridge
5. Start ham in iobroker
6. persist and accessories folder are created by iobroker
7. if you start HB again outside ioB - be sure to delete both folders again 

Thank you for your patience, @Apollon77

**Comment by Apollon77** [comment]
Thank you, I will add something to the Readme for Global mode (or would you ind doing a PR?)

**Comment by skatehouse** [comment]
> 
> 
> Thank you, I will add something to the Readme for Global mode (or would you ind doing a PR?)

Maybe...but i´m still figuring out ..... now it starts, but no connection to alexa
