### ISSUE TITLE
Global Homebridge Path

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.ham#168]
I can't start it in global mode. It's not entirely clear, should the global HB be started or will it be started by iobroker? I tried all sorts of ways:
/var/lib/homebridge/
/usr/lib/node_modules/homebridge/
nothing helps. I tried to set full access to the folder /var/lib/homebridge/ (chmod-R 777 /var/lib/homebridge/), it also did not help. all time error

ham.0 | 2021-06-11 18:33:09.408 | error | (15295) Exception-Code: MODULE_NOT_FOUND: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/
-- | -- | -- | --
ham.0 | 2021-06-11 18:33:09.407 | error | (15295) Error: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/iobroker.ham/main.js at
ham.0 | 2021-06-11 18:33:09.404 | error | (15295) unhandled promise rejection: Cannot find module '/var/lib/homebridge/lib/user' Require stack: - /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js - /opt/iobroker/node_modules/iobro
ham.0 | 2021-06-11 18:33:09.403 | error | (15295) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

![image](https://user-images.githubusercontent.com/37106885/121712581-9240b300-cae4-11eb-88f3-f96c8d3f9f2b.png)

**Comment by Apollon77** [comment]
In all modes homebridge is started by iobroker. Else the adapter can not "sneak in" to interact with all the plugins.

Especialyl for global mode this means:
* stop homebridge on the system
* set the correct paths
* make sure that all global read and especially write directories (persistent stuff) are also read/writebale by the iobroker user where iobroker runs on!
* make sure to have the correct global version og homebridge running that matches to the adapter verison - check changelog of iobroker plugin
If the patch's are correct for your system you need to find out and this will highly depend on how and where homebridge was installed on your system.

**Comment by Anzic23** [comment]
Note to me, and to others:
1. `sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x`
2. `sudo hb-service install --user homebridge` - I'm not sure, maybe it doesn't need to be done at all.
3. after installing homebridge
```
sudo hb-service stop
sudo chmod 777 -R /var/lib/homebridge/
sudo chmod 777 -R /usr/lib/node_modules/homebridge
```
in iobroker
Global Homebridge Path:
/usr/lib/node_modules/homebridge

Global Homebridge Config Directory Path:
/var/lib/homebridge

**Comment by Apollon77** [comment]
added to readme, thank you!
