### ISSUE TITLE
virtualCommandLine not working

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.ham#170]
**Describe the bug**  
https://github.com/ioBroker/ioBroker.js-controller/issues/844

**Expected behavior**  
if I add the --tls-min-v1.0 command to virtualCommandLine, the adapter should start without crashing
**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/122122392-69e2ec80-ce35-11eb-8f56-90f074250820.png)

**Versions:**  
 - Adapter version: 4.0.2
 - JS-Controller version: 3.3.12
 - Node version: v12.22.1
 - Operating system: docker

**Comment by Apollon77** [comment]
What is the "virtualCommandLine"?

**Comment by Anzic23** [comment]
> What is the "virtualCommandLine"?

![image](https://user-images.githubusercontent.com/37106885/122123248-7156c580-ce36-11eb-9188-dea3af6a7269.png)

**Comment by Anzic23** [comment]
in homebridge, it works perfectly!
![image](https://user-images.githubusercontent.com/37106885/122123362-92b7b180-ce36-11eb-9c45-d6fecdfc8cb6.png)

**Comment by Apollon77** [comment]
Hm ... I'm not sure if this is the same!!

virtual (!!) command line is kind of injecting command line parameters just for homebridget after the process was started, so it is NOT "node-options" used when the process gets started!

SO this can not work that way
