### ISSUE TITLE
Übersichtlichere Objektstruktur 

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.ham#183]
Jedes Plugin sollte seine "Geräte" in einem separaten "Ordner" unterhalb von ham.0 erzeugen, sonst wird es unterhalb von ham.0 bei vielen Plugins und Geräten schnell unübersichtlich.

ham.0
- Plugin 1
   - Gerät 1
   - Gerät 2
 - Plugin 2
   - Gerät 1
   - Gerät 2

**Comment by Apollon77** [comment]
Das ist leider nicht so simpel weil der Code in dem Teil nichts von Plugins, Platformen oder so weiss sondern primär Accessories kennt und das ist die "geräteebene". Mit viel Zeit kann man mal versuchen herauszubekommen wie man das ggf. generisch genug für höhere Ebenen zusammenfassen kann bzw diese gruppierungsebene herauszufinden. nehme PRs dazu gern

**Comment by Apollon77** [comment]
habe nochmal geschaut. Ist effektiv nicht möglich, weil an der Stelle wo der Adapter die Accessories rausfischt ist keine Information vorhanden von welchem Plugin Sie registriert wurden

**Comment by RP70DP** [comment]
Okay, danke fürs prüfen!
