### ISSUE TITLE
HAM does not start

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.ham#21]
host.iobroker | 2019-03-12 00:39:46.027 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-03-12 00:39:46.027 | error | by controller[0]: path: '/root/.homebridge/persist' }
Caught | 2019-03-12 00:39:46.027 | error | by controller[0]: code: 'EACCES',
Caught | 2019-03-12 00:39:46.025 | error | by controller[0]: syscall: 'mkdir',
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: errno: -13,
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:175:27)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:232:35)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:256:9)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at Object.init (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at LocalStorage.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
Caught | 2019-03-12 00:39:46.024 | error | by controller[0]: at LocalStorage.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
Caught | 2019-03-12 00:39:46.023 | error | by controller[0]: at LocalStorage.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:642:20)
Caught | 2019-03-12 00:39:46.023 | error | by controller[0]: at Function.sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
Caught | 2019-03-12 00:39:46.023 | error | by controller[0]: at Object.mkdirSync (fs.js:752:3)
Caught | 2019-03-12 00:39:46.023 | error | by controller[0]: { Error: EACCES: permission denied, mkdir '/root/.homebridge/persist'
  |   |   |  

What's the matter?

**Comment by Apollon77** [comment]
EACCES means permission problems. You need to make sure when using global mode that the user where iobroker is running under can access those files

**Comment by Mr-REM-Esq** [comment]
I apologize, but how can I see the user where iobroker is running under? 
I used the recommended script to install ibroker (curl -sL https://raw.githubusercontent.com/ioBroker/ioBroker/stable-installer/installer.sh | bash -) and figured that ioBroker would work under the root.

**Comment by Apollon77** [comment]
Then try to

chmod-R 777 /root/.homebridge

Tonhöhe Access to all users
