### ISSUE TITLE
1 fehlendes "nicht" erkanntes Gerät

### ISSUE THREAD

**Issue by kaeffin** [ioBroker/ioBroker.ham#224]
Hallo ich habe heute den ioBroker.ham adapter hinzugefügt und nutze die homebridge-ewelink lib.

Leider wird nur 1 Gerät "erkannt". Ich bin mir nicht sicher ob das jetzt an der Bibliothek liegt oder am Adapter. Oder wahrscheinlich an mir ;D
Zumindest sieht es so im Objektbaum aus:
![image](https://user-images.githubusercontent.com/54470977/134805133-04cd99f8-9310-4ab3-88da-489e749aab07.png)

Switch "Gartenlicht" läuft einwandfrei.
und der zweite leider nicht.  Die Geräte sind identisch.  Also auch ein Switch.

Vielleicht kann mir da jemand helfen ?
Vielen Dank.

Hier die Logs dazu:

`
ham.0 | 2021-09-26 12:46:34.652 | info | (7723) stateChange ham.0.Gartenlicht.Gartenlicht-History.S2R1 {"val":"3x8AAAAAAAAsZwAnAQ4BHQDADwAAAAAAAAAAAQE=","ack":true,"ts":1632653194634,"q":0,"from":"system.adapter.ham.0","user":"system.user.a
-- | -- | -- | --
ham.0 | 2021-09-26 12:46:34.649 | info | (7723) stateChange ham.0.Deviceee7d2b.Deviceee7d2b-History.S2R1 {"val":"3x8AAAAAAAArZwAnAQ4BGADADwAAAAAAAAAAAQE=","ack":true,"ts":1632653194632,"q":0,"from":"system.adapter.ham.0","user":"system.user
ham.0 | 2021-09-26 12:46:34.588 | info | (7723) stateChange ham.0.Gartenlicht.Switch.On {"val":false,"ack":true,"ts":1632653194578,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187086}
ham.0 | 2021-09-26 12:46:34.582 | info | (7723) stateChange ham.0.Deviceee7d2b.Switch.On {"val":false,"ack":true,"ts":1632653194577,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187080}
ham.0 | 2021-09-26 12:46:27.289 | info | (7723) stateChange ham.0.Gartenlicht.Gartenlicht-History.S2R2 {"val":null,"ack":true,"ts":1632653187087,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187087}
ham.0 | 2021-09-26 12:46:27.288 | info | (7723) stateChange ham.0.Gartenlicht.Gartenlicht-History.S2R1 {"val":"qRsAAAAAAAAsZwAnAQ4BHADADwAAAAAAAAAAAQE=","ack":true,"ts":1632653187087,"q":0,"from":"system.adapter.ham.0","user":"system.user.a
ham.0 | 2021-09-26 12:46:27.287 | info | (7723) stateChange ham.0.Gartenlicht.Gartenlicht-History.Name {"val":"Gartenlicht History","ack":true,"ts":1632653187087,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187
ham.0 | 2021-09-26 12:46:27.271 | info | (7723) stateChange ham.0.Gartenlicht.Switch.Name {"val":"","ack":true,"ts":1632653187086,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187086}
ham.0 | 2021-09-26 12:46:27.269 | info | (7723) stateChange ham.0.Gartenlicht.Switch.On {"val":false,"ack":true,"ts":1632653187086,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187086}
ham.0 | 2021-09-26 12:46:27.267 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Product-Data {"val":null,"ack":true,"ts":1632653187086,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187086}
ham.0 | 2021-09-26 12:46:27.266 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Software-Revision {"val":"","ack":true,"ts":1632653187085,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187085}
ham.0 | 2021-09-26 12:46:27.265 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1632653187085,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187085}
ham.0 | 2021-09-26 12:46:27.264 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Configured-Name {"val":"","ack":true,"ts":1632653187085,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187085}
ham.0 | 2021-09-26 12:46:27.263 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.App-Matching-Identifier {"val":null,"ack":true,"ts":1632653187084,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":163265
ham.0 | 2021-09-26 12:46:27.260 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1632653187084,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187084}
ham.0 | 2021-09-26 12:46:27.258 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Configured-Name {"val":"Gartenlicht","ack":true,"ts":1632653187083,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326
ham.0 | 2021-09-26 12:46:27.256 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Firmware-Revision {"val":"3.4.1","ack":true,"ts":1632653187083,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":163265318
ham.0 | 2021-09-26 12:46:27.233 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Serial-Number {"val":"1000ee9827SWX","ack":true,"ts":1632653187082,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326
ham.0 | 2021-09-26 12:46:27.231 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Name {"val":"Gartenlicht","ack":true,"ts":1632653187082,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187082}
ham.0 | 2021-09-26 12:46:27.229 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Model {"val":"0185 (PSF-B01-GL)","ack":true,"ts":1632653187082,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":163265318
ham.0 | 2021-09-26 12:46:27.227 | info | (7723) stateChange ham.0.Gartenlicht.Accessory-Information.Manufacturer {"val":"coolkit","ack":true,"ts":1632653187081,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":163265318708
ham.0 | 2021-09-26 12:46:27.226 | info | (7723) stateChange ham.0.Deviceee7d2b.Deviceee7d2b-History.S2R2 {"val":null,"ack":true,"ts":1632653187081,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187081}
ham.0 | 2021-09-26 12:46:27.224 | info | (7723) stateChange ham.0.Deviceee7d2b.Deviceee7d2b-History.S2R1 {"val":"DRoAAAAAAAArZwAnAQ4BFwDADwAAAAAAAAAAAQE=","ack":true,"ts":1632653187081,"q":0,"from":"system.adapter.ham.0","user":"system.user
ham.0 | 2021-09-26 12:46:27.210 | info | (7723) stateChange ham.0.Deviceee7d2b.Deviceee7d2b-History.Name {"val":"Deviceee7d2b History","ack":true,"ts":1632653187080,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653
ham.0 | 2021-09-26 12:46:27.208 | info | (7723) stateChange ham.0.Deviceee7d2b.Switch.Name {"val":"","ack":true,"ts":1632653187080,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187080}
ham.0 | 2021-09-26 12:46:27.206 | info | (7723) stateChange ham.0.Deviceee7d2b.Switch.On {"val":false,"ack":true,"ts":1632653187080,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187080}
ham.0 | 2021-09-26 12:46:27.204 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Product-Data {"val":null,"ack":true,"ts":1632653187079,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187079}
ham.0 | 2021-09-26 12:46:27.203 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Software-Revision {"val":"","ack":true,"ts":1632653187079,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187079
ham.0 | 2021-09-26 12:46:27.191 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1632653187078,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187078
ham.0 | 2021-09-26 12:46:27.189 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Configured-Name {"val":"","ack":true,"ts":1632653187078,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187078}
ham.0 | 2021-09-26 12:46:27.187 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.App-Matching-Identifier {"val":null,"ack":true,"ts":1632653187078,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326
ham.0 | 2021-09-26 12:46:27.178 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1632653187077,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187077}
ham.0 | 2021-09-26 12:46:27.176 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Configured-Name {"val":"Deviceee7d2b","ack":true,"ts":1632653187077,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":163
ham.0 | 2021-09-26 12:46:27.167 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Firmware-Revision {"val":"3.4.1","ack":true,"ts":1632653187076,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326531
ham.0 | 2021-09-26 12:46:27.159 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Serial-Number {"val":"1000ee7d2bSWX","ack":true,"ts":1632653187076,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632
ham.0 | 2021-09-26 12:46:27.150 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Name {"val":"Deviceee7d2b","ack":true,"ts":1632653187076,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1632653187076}
ham.0 | 2021-09-26 12:46:27.142 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Model {"val":"0185 (PSF-B01-GL)","ack":true,"ts":1632653187075,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326531
ham.0 | 2021-09-26 12:46:27.136 | info | (7723) stateChange ham.0.Deviceee7d2b.Accessory-Information.Manufacturer {"val":"coolkit","ack":true,"ts":1632653187074,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":16326531870
ham.0 | 2021-09-26 12:46:27.031 | warn | (7723) State "ham.0.Gartenlicht.Gartenlicht-History.S2R2" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.029 | warn | (7723) State "ham.0.Gartenlicht.Gartenlicht-History.S2R1" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.028 | warn | (7723) State "ham.0.Gartenlicht.Gartenlicht-History.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.026 | warn | (7723) State "ham.0.Gartenlicht.Switch.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.025 | warn | (7723) State "ham.0.Gartenlicht.Switch.On" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.023 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Product-Data" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.015 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Software-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.014 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Hardware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.012 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Configured-Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.011 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.App-Matching-Identifier" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.010 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Accessory-Flags" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.008 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Configured-Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.007 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Firmware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.005 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Serial-Number" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.004 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.002 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Model" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.001 | warn | (7723) State "ham.0.Gartenlicht.Accessory-Information.Manufacturer" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:27.000 | warn | (7723) State "ham.0.Deviceee7d2b.Deviceee7d2b-History.S2R2" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.998 | warn | (7723) State "ham.0.Deviceee7d2b.Deviceee7d2b-History.S2R1" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.997 | warn | (7723) State "ham.0.Deviceee7d2b.Deviceee7d2b-History.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.996 | warn | (7723) State "ham.0.Deviceee7d2b.Switch.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.994 | warn | (7723) State "ham.0.Deviceee7d2b.Switch.On" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.993 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Product-Data" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.992 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Software-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.990 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Hardware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.989 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Configured-Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.988 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.App-Matching-Identifier" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.986 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Accessory-Flags" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.985 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Configured-Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.983 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Firmware-Revision" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.982 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Serial-Number" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.980 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Name" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.979 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Model" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.977 | warn | (7723) State "ham.0.Deviceee7d2b.Accessory-Information.Manufacturer" has no existing object, this might lead to an error in future versions
ham.0 | 2021-09-26 12:46:26.303 | info | (7723) updateState Gartenlicht.Gartenlicht-History.S2W2: value = null /common= {"type":"string","read":false,"write":true,"role":"text","name":"S2W2","unit":""}
ham.0 | 2021-09-26 12:46:26.301 | info | (7723) updateState Gartenlicht.Gartenlicht-History.S2W1: value = null /common= {"type":"string","read":false,"write":true,"role":"text","name":"S2W1","unit":""}
ham.0 | 2021-09-26 12:46:26.299 | info | (7723) updateState Gartenlicht.Gartenlicht-History.S2R2: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"S2R2","unit":""}
ham.0 | 2021-09-26 12:46:26.298 | info | (7723) updateState Gartenlicht.Gartenlicht-History.S2R1: value = qRsAAAAAAAAsZwAnAQ4BHADADwAAAAAAAAAAAQE= /common= {"type":"string","read":true,"write":false,"role":"text","name":"S2R1","unit":""}
ham.0 | 2021-09-26 12:46:26.297 | info | (7723) updateState Gartenlicht.Gartenlicht-History.Name: value = Gartenlicht History /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.296 | info | (7723) updateChannel Gartenlicht.Gartenlicht-History: name = Gartenlicht History
ham.0 | 2021-09-26 12:46:26.295 | info | (7723) updateState Gartenlicht.Switch.Name: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.293 | info | (7723) updateState Gartenlicht.Switch.On: value = false /common= {"type":"boolean","read":true,"write":true,"role":"switch","name":"On","unit":""}
ham.0 | 2021-09-26 12:46:26.292 | info | (7723) updateChannel Gartenlicht.Switch: name =
ham.0 | 2021-09-26 12:46:26.291 | info | (7723) updateState Gartenlicht.Accessory-Information.Product-Data: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"Product Data","unit":""}
ham.0 | 2021-09-26 12:46:26.290 | info | (7723) updateState Gartenlicht.Accessory-Information.Software-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Software Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.289 | info | (7723) updateState Gartenlicht.Accessory-Information.Hardware-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Hardware Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.287 | info | (7723) updateState Gartenlicht.Accessory-Information.Configured-Name: value = /common= {"type":"string","read":true,"write":true,"role":"text","name":"Configured Name","unit":""}
ham.0 | 2021-09-26 12:46:26.286 | info | (7723) updateState Gartenlicht.Accessory-Information.App-Matching-Identifier: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"App Matching Identifier","unit":""
ham.0 | 2021-09-26 12:46:26.284 | info | (7723) updateState Gartenlicht.Accessory-Information.Accessory-Flags: value = 0 /common= {"type":"number","min":0,"max":4294967295,"read":true,"write":false,"role":"value","name":"Accessory Flags","u
ham.0 | 2021-09-26 12:46:26.283 | info | (7723) updateState Gartenlicht.Accessory-Information.Configured-Name: value = Gartenlicht /common= {"type":"string","read":true,"write":true,"role":"text","name":"Configured Name","unit":""}
ham.0 | 2021-09-26 12:46:26.282 | info | (7723) updateState Gartenlicht.Accessory-Information.Firmware-Revision: value = 3.4.1 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Firmware Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.281 | info | (7723) updateState Gartenlicht.Accessory-Information.Serial-Number: value = 1000ee9827SWX /common= {"type":"string","read":true,"write":false,"role":"text","name":"Serial Number","unit":""}
ham.0 | 2021-09-26 12:46:26.280 | info | (7723) updateState Gartenlicht.Accessory-Information.Name: value = Gartenlicht /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.279 | info | (7723) updateState Gartenlicht.Accessory-Information.Model: value = 0185 (PSF-B01-GL) /common= {"type":"string","read":true,"write":false,"role":"text","name":"Model","unit":""}
ham.0 | 2021-09-26 12:46:26.277 | info | (7723) updateState Gartenlicht.Accessory-Information.Manufacturer: value = coolkit /common= {"type":"string","read":true,"write":false,"role":"text","name":"Manufacturer","unit":""}
ham.0 | 2021-09-26 12:46:26.276 | info | (7723) updateState Gartenlicht.Accessory-Information.Identify: value = true /common= {"type":"boolean","read":false,"write":true,"role":"button","name":"Identify","unit":""}
ham.0 | 2021-09-26 12:46:26.275 | info | (7723) updateChannel Gartenlicht.Accessory-Information: name =
ham.0 | 2021-09-26 12:46:26.272 | info | (7723) updateDev Gartenlicht: name = Gartenlicht /type= 1
ham.0 | 2021-09-26 12:46:26.260 | info | (7723) updateState Deviceee7d2b.Deviceee7d2b-History.S2W2: value = null /common= {"type":"string","read":false,"write":true,"role":"text","name":"S2W2","unit":""}
ham.0 | 2021-09-26 12:46:26.258 | info | (7723) updateState Deviceee7d2b.Deviceee7d2b-History.S2W1: value = null /common= {"type":"string","read":false,"write":true,"role":"text","name":"S2W1","unit":""}
ham.0 | 2021-09-26 12:46:26.257 | info | (7723) updateState Deviceee7d2b.Deviceee7d2b-History.S2R2: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"S2R2","unit":""}
ham.0 | 2021-09-26 12:46:26.256 | info | (7723) updateState Deviceee7d2b.Deviceee7d2b-History.S2R1: value = DRoAAAAAAAArZwAnAQ4BFwDADwAAAAAAAAAAAQE= /common= {"type":"string","read":true,"write":false,"role":"text","name":"S2R1","unit":""}
ham.0 | 2021-09-26 12:46:26.255 | info | (7723) updateState Deviceee7d2b.Deviceee7d2b-History.Name: value = Deviceee7d2b History /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.253 | info | (7723) updateChannel Deviceee7d2b.Deviceee7d2b-History: name = Deviceee7d2b History
ham.0 | 2021-09-26 12:46:26.252 | info | (7723) updateState Deviceee7d2b.Switch.Name: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.251 | info | (7723) updateState Deviceee7d2b.Switch.On: value = false /common= {"type":"boolean","read":true,"write":true,"role":"switch","name":"On","unit":""}
ham.0 | 2021-09-26 12:46:26.249 | info | (7723) updateChannel Deviceee7d2b.Switch: name =
ham.0 | 2021-09-26 12:46:26.247 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Product-Data: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"Product Data","unit":""}
ham.0 | 2021-09-26 12:46:26.246 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Software-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Software Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.245 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Hardware-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Hardware Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.244 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Configured-Name: value = /common= {"type":"string","read":true,"write":true,"role":"text","name":"Configured Name","unit":""}
ham.0 | 2021-09-26 12:46:26.242 | info | (7723) updateState Deviceee7d2b.Accessory-Information.App-Matching-Identifier: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"App Matching Identifier","unit":"
ham.0 | 2021-09-26 12:46:26.240 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Accessory-Flags: value = 0 /common= {"type":"number","min":0,"max":4294967295,"read":true,"write":false,"role":"value","name":"Accessory Flags","
ham.0 | 2021-09-26 12:46:26.238 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Configured-Name: value = Deviceee7d2b /common= {"type":"string","read":true,"write":true,"role":"text","name":"Configured Name","unit":""}
ham.0 | 2021-09-26 12:46:26.236 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Firmware-Revision: value = 3.4.1 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Firmware Revision","unit":""}
ham.0 | 2021-09-26 12:46:26.235 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Serial-Number: value = 1000ee7d2bSWX /common= {"type":"string","read":true,"write":false,"role":"text","name":"Serial Number","unit":""}
ham.0 | 2021-09-26 12:46:26.233 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Name: value = Deviceee7d2b /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-09-26 12:46:26.232 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Model: value = 0185 (PSF-B01-GL) /common= {"type":"string","read":true,"write":false,"role":"text","name":"Model","unit":""}
ham.0 | 2021-09-26 12:46:26.230 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Manufacturer: value = coolkit /common= {"type":"string","read":true,"write":false,"role":"text","name":"Manufacturer","unit":""}
ham.0 | 2021-09-26 12:46:26.229 | info | (7723) updateState Deviceee7d2b.Accessory-Information.Identify: value = true /common= {"type":"boolean","read":false,"write":true,"role":"button","name":"Identify","unit":""}
ham.0 | 2021-09-26 12:46:26.224 | info | (7723) updateChannel Deviceee7d2b.Accessory-Information: name =
ham.0 | 2021-09-26 12:46:26.219 | info | (7723) updateDev Deviceee7d2b: name = Deviceee7d2b /type= 1
ham.0 | 2021-09-26 12:46:22.472 | info | (7723) All Libraries installed/updated
ham.0 | 2021-09-26 12:46:22.463 | info | (7723) Install/Update homebridge-ewelink
ham.0 | 2021-09-26 12:46:22.461 | info | (7723) Install/Update the following Libraries: homebridge-ewelink
ham.0 | 2021-09-26 12:46:22.405 | info | (7723) starting. Version 4.0.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.22.1, js-controller: 3.2.16
`

**Comment by Apollon77** [comment]
Bitte Debug Log posten. aber der Adapter arbeitet generell erst einmal generisch ... heisst - was vom Homebridge Pugin gemeldet wird sollte auch auftauchen

**Comment by kaeffin** [comment]
Danke für die schnelle Antwort. Es funktioniert alles einwandfrei. Der Objektbaum sieht zwar immernoch so aus wie in meinem Bild aber wenn ich über Vis den Objektbaum öffne um ein Widget mit einem Objekt zu verknüpfen ist alles vorhanden.

**Comment by Apollon77** [comment]
<Dann mal im Admin reload drücken bei den Objekten?
