### ISSUE TITLE
Another problem with rights

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.ham#24]
HAM works in global mode. ioBroker is installed using the recommended script, therefore it works as "iobroker" user. I tried to update Homebridge.

<img width="1002" alt="Снимок экрана 2019-03-29 в 22 33 30" src="https://user-images.githubusercontent.com/42520242/55258052-cb2d3e00-5272-11e9-992d-97181c17db32.png">

How to solve this problem?

**Comment by Apollon77** [comment]
I thought in global mode it is needed to install homebridge as real Sudo and root?!

I even du not know the command line you used? Where is this from?

**Comment by Mr-REM-Esq** [comment]
When I installed the ioBroker I used the recommendations from [here](https://github.com/ioBroker/ioBroker/wiki/Installation): 
"Then execute
curl -sL https://raw.githubusercontent.com/ioBroker/ioBroker/stable-installer/installer.sh | bash -".

This script installed an ioBroker with the user "ioBroker". This user has insufficient rights.

**Comment by Apollon77** [comment]
Yes because it is never meaned to also install a global homebridge with this user ... Install a global homebridge as normal (root or however) and then you need to allow access to the config directory (mostly .homebridge in the respective user directory) that iobroker user is allowed to access the files there.
Please do not mix things! iobroker is only to run iobroker.

**Comment by Mr-REM-Esq** [comment]
But I installed Homebridge as normal (root). 

root@iobroker:/usr/lib/node_modules/homebridge# ls -la
итого 84
drwxr-xr-x  7 root root  4096 апр  1 22:30 .
drwxr-xr-x  7 root root  4096 апр  1 22:32 ..
drwxr-xr-x  2 root root  4096 апр  1 22:30 bin
-rw-r--r--  1 root root    14 окт 26  1985 CNAME
-rw-r--r--  1 root root   599 окт 26  1985 config-sample.json
drwxr-xr-x  2 root root  4096 апр  1 22:30 .github
-rw-r--r--  1 root root 12462 окт 26  1985 index.html
drwxr-xr-x  3 root root  4096 апр  1 22:30 lib
-rw-r--r--  1 root root 10172 окт 26  1985 LICENSE
drwxr-xr-x 40 root root  4096 апр  1 22:30 node_modules
-rw-r--r--  1 root root  1570 апр  1 22:30 package.json
-rw-r--r--  1 root root 13053 окт 26  1985 README.md
drwxr-xr-x  6 root root  4096 апр  1 22:30 website
root@iobroker:/usr/lib/node_modules/homebridge#

And I gave all the necessary permissions to the configuration file.

root@iobroker:/home/iobroker/.homebridge# ls -la
итого 24
drwxr-xr-x 4 iobroker iobroker 4096 апр  1 23:04 .
drwxr-xr-x 6 iobroker iobroker 4096 мар 13 00:59 ..
drwxr-xr-x 2 iobroker iobroker 4096 апр  1 23:05 accessories
-rw-r--r-- 1 iobroker iobroker  359 апр  1 23:04 auth.json
-rw-r--r-- 1 iobroker iobroker  358 мар 13 01:01 config.json
drwxr-xr-x 2 iobroker iobroker 4096 апр  1 23:04 persist
root@iobroker:/home/iobroker/.homebridge#

<img width="1122" alt="Снимок экрана 2019-04-01 в 23 05 56" src="https://user-images.githubusercontent.com/42520242/55356110-bb139980-54d2-11e9-9732-0131857dc200.png">

But this is still not enough.

<img width="1259" alt="Снимок экрана 2019-04-01 в 23 07 25" src="https://user-images.githubusercontent.com/42520242/55356263-07f77000-54d3-11e9-958c-b162f751b586.png">

Even if I manage to run Homebridge, HAM will launched it from the user "ioBroker".

Could you tell me the exact sequence of actions that will lead to success?

**Comment by Apollon77** [comment]
This is a good question ... I need to look into this deeper.

Maybe you want to try the new "local mode" in 1.1.1? it imstalls a full homebridge in ionroker and offers it as bridge, so you could replace the global one with it
