### ISSUE TITLE
Value Polling Interval doesn't work

### ISSUE THREAD

**Issue by DuBass858** [ioBroker/ioBroker.ham#241]
**Describe the bug**  
I set the polling interval as 30sec, but it didn't change, so every 0.5-5 sec get new states

**Expected behavior**  
Changed the polling interval

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/77126974/135756054-68070892-90a9-4649-ba6b-fb920dadd857.png)

Check my log:
[iobroker.2021-10-03.zip](https://github.com/ioBroker/ioBroker.ham/files/7273433/iobroker.2021-10-03.zip)

**Versions:**  
 - Plugin: homebridge-broadlink-heater-cooler
 - Adapter version: v4.0.2
 - JS-Controller version: 3.3.18
 - Node version: v14.18.0
 - Operating system:  Raspberry Pi OS

**Comment by Apollon77** [comment]
The "polling intervall" is just a fallback for Plugins that do not support "pushing new values". These plugins then can only be polled.
So if the data come more often this is "as designed" and means that the plugin pushs new values actively. is it about that?

**Comment by DuBass858** [comment]
Understand, thanks
