### ISSUE TITLE
homebridge im iobroker benutzen

### ISSUE THREAD

**Issue by candlestorm** [ioBroker/ioBroker.ham#259]
Hallo Zusammen,

es ist kein Bug sondern eine allgemeine Frage.
Ich habe Grundkenntnisse bezüglich Linux/iobroker und co.
Derzeit nutze ich Yahka im iobroker, würde jedoch gerne auf Homebridge wechseln.

Ich habe den Ham Adapter installiert und würde ihn gerne als lokale Version nutzen. Wo konfiguriere ich denn den Namen und PIN der Homebridge? Wie aktiviere ich denn im AdminTab den neuen Reiter Homebridge? Reicht es aus, wenn ich die Plugins im UserInterface des Adapters hinzufüge und der Adapter installiert sie anschließend selbst?

Tut mir leid für die "doofen" Fragen aber das ist für mich nicht selbsterklärend.
Ich würde gerne hauptsächlich das Homematic plugin benutzen.

Viele Grüße!

**Comment by Apollon77** [comment]
Am besten dazu  im Forum einen Thread öffnen, da ist das besser diskutiert als hier.

generell ist yahka und homebridge unterschiedliche Dinge!!

Yahka ist dazu da ioBroker geräte in Apple Home zu nutzen, homebrudge ist dazu da andere geräte wofür es Plugins gibt im Apple Home zu nutzen.

ALso was willst Du denn?
