### ISSUE TITLE
ioBroker und bereits installierte Homebridge

### ISSUE THREAD

**Issue by GitHubNullFear** [ioBroker/ioBroker.ham#260]
Guten Tag, 

Ich habe aktuell eine Homebridge am laufen und wurde diese nun gerne mit iobroker.ham in den iobroker integrieren. Bekomme immer wieder die Meldung das iobroker.ham nicht verbinden kann da Homebridge bereits läuft. Stoppe ich die Bridge, startet iobroker.ham die Homebridge neu. Dann sind aber leider meine ganzen Geräte weg. 

Mache ich da irgendetwas falsch?

**Comment by Apollon77** [comment]
Also wenn du die Bridge in iobroker.ham haben willst musst du "Homebridge" an sich stoppen und nur den Adapter starten. Der startet dann homebridge und klinkt sich ein. ... wnen ich Dein problem richtig verstanden habe ...

**Comment by GitHubNullFear** [comment]
Alles klar habe ich inzwischen hinbekommen. Leider habe ich nun kein log mehr und die Geräte sind auf der Bridge auch nicht mehr zu sehen. 

Desweiteren schickt hue alle 5sec nen statechange den ich nicht verstehe. 

Danke schonmal für die Hilfe.

**Comment by Apollon77** [comment]
Stelle ham Adapter auf Debug Logging ... Dann hast Du die Logs von homebride bei ioBroker

**Comment by GitHubNullFear** [comment]
Guten Morgen, danke für die Info.

Das dieser Eintrag alle 5 sec generiert wird ist normal ?

lookup id: Philips-hue.Philips-hue.Last-Updated

Danke für die Info.

**Comment by Apollon77** [comment]
so eine Teilzeile rausgerissen kann ich schlecht bewerten , aber wenn das kommt das wird von irgendeiner "Seite" da was geändert ... also spontan: Ja

**Comment by GitHubNullFear** [comment]
Alles klar sorry. 

Musste leider wieder Abstand von deinem Adapter nehmen. Aqara LeakSensor wird zwar unterstütz aber leider ohne Batteriestatus.
Weiterhin viel Erfolg

**Comment by Apollon77** [comment]
Naja ... wenns das homebridge Plugin nicht kann, kanns der Adapter auch nicht ... oder was meinst Du? Also Eröffne Issue beim homebridge Plugin :-)
