### ISSUE TITLE
Feature-Request insecure mode

### ISSUE THREAD

**Issue by Alex18081** [ioBroker/ioBroker.ham#28]
homebridge-config-ui-x braucht "insecure mode" für Accessoires Seite.
"To enable accessory control you must be running Homebridge in insecure mode:
homebridge -I"
Gabs anscheint schon ein versuch :)
https://github.com/ioBroker/ioBroker.ham/issues/14

**Comment by Apollon77** [comment]
Ja ääähm installier doch mal vom Githbu ... geht die Version bei Dir? Hast du das das Flag?

**Comment by Alex18081** [comment]
Installiert v1.0.1, funktioniert aber finde kein Flag für insecure mode.
Node v8.16.0, sonst alles Aktuellste

**Comment by Apollon77** [comment]
Nach installation mal "iobroker upload ham" gemacht?

**Comment by Alex18081** [comment]
ja, habe ich

**Comment by Apollon77** [comment]
ann sollte eine Auswahl da sein unter der Stelle wo man wählt ob globaler oder lokaler modus

**Comment by Alex18081** [comment]
http://prntscr.com/o7id2k

**Comment by Apollon77** [comment]
Ok .. nicht darunter sonder rechts davon. 

Verwenden Sie den unsicheren Modus ... unsicher = insecure ;-)

**Comment by Alex18081** [comment]
ach das wahr es, alles klar 8-) Ich war da zimlich unsicher mit diesem unsicherem Modus )))

**Comment by Alex18081** [comment]
Accessory Control bei config-ui-x komt trozdem nicht.. :(

**Comment by Apollon77** [comment]
Ja weil die es wirklich als Startparameter des Startenden prozesses haben wollen ... Sorry aber das geht nicht sooo simpel.

DU könntest mal versuchen irgendwie eine dauerhafte Environment Variable im System zu setzen (frag mich aber gerade nicht wie):
UIX_INSECURE_MODE = '1'

**Comment by Apollon77** [comment]
Ok, update. I have a very experimental new verison on Github. I still work on testing for windows and there may be problems, especially in global mode.
And it still needs detailed testing, but I added an option to specify command line parameters there that are added to the system one's. In theory your case should work when you enter "-I" there ... Please give it a try now or in some days after I finalized the version more.

**Comment by Alex18081** [comment]
Adapter kann nicht starten.

Caught	2019-07-02 23:43:51.265	error	by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
Caught	2019-07-02 23:43:51.265	error	by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
Caught	2019-07-02 23:43:51.265	error	by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2019-07-02 23:43:51.265	error	by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
Caught	2019-07-02 23:43:51.265	error	by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught	2019-07-02 23:43:51.264	error	by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2019-07-02 23:43:51.264	error	by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
Caught	2019-07-02 23:43:51.264	error	by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught	2019-07-02 23:43:51.264	error	by controller[0]: at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2693:25)
Caught	2019-07-02 23:43:51.264	error	by controller[0]: at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:173:39)
Caught	2019-07-02 23:43:51.263	error	by controller[0]: TypeError: Cannot read property 'registerExistingAccessory' of undefined
ham.0	2019-07-02 23:43:51.217	warn	Exception: TypeError: Cannot read property 'registerExistingAccessory' of undefined

**Comment by Apollon77** [comment]
Ok i will check :-(

**Comment by Apollon77** [comment]
Please retry, should be fixed

**Comment by Alex18081** [comment]
ok, Adapter startet!
allerdigs sobald ich was bei "virtualCommandLine" eintrage, bekomme ich folgende fehler im Log.


Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Socket.onpacket  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Socket.onack  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Socket.that.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:25)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5289:18)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Adapter.emit (events.js:208:7)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at emitNone (events.js:106:13)
Caught | 2019-07-03 16:47:50.515 | error | by controller[0]:     at Adapter.main (/opt/iobroker/node_modules/iobroker.ham/main.js:199:13)
Caught | 2019-07-03 16:47:50.514 | error | by controller[0]: TypeError: stringArgv is not a function

**Comment by Apollon77** [comment]
hm ... please retry

**Comment by Alex18081** [comment]
Super, jetzt gehts!
Danke!

**Comment by Alex18081** [comment]
Es hakt immer noch irgendwo. Menü Gärete ist vorhanden, aber zeigt keine Gärete. Bei manuelen start sind Gärete da.

ham - http://prntscr.com/oa3z2o
Terminal - http://prntscr.com/oa41i7

**Comment by Alex18081** [comment]
das habe ich noch


Caught | 2019-07-03 17:50:04.390 | error | by controller[1]: [2019-7-3 17:49:57] Plugin  /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does  not contain the keyword 'homebridge-plugin'.
-- | -- | -- | --
Caught | 2019-07-03 17:50:04.390 | error | by controller[0]: [2019-7-3 17:49:57] Plugin  /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper  package.json does not contain the keyword 'homebridge-plugin'

**Comment by Apollon77** [comment]
Also die Meldung ist egal.

Warum das jetzt nicht tut kann ich dir nicht sagen ... da müsste ich jetzt sehr tief ins Plugin schauen wie es tut. Welchen Modus nutzt Du eigentlich?

**Comment by Alex18081** [comment]
Globaler Modus. Homebridge vorinstalliert.

**Comment by Apollon77** [comment]
kannst Du mal versuchen ob es ggf mit dem neuen "Lokalen Modus" geht?

**Comment by Alex18081** [comment]
ham.0 | 2019-07-04 00:03:15.977 | warn | Exception: TypeError: Cannot read property 'username' of undefined
-- | -- | -- | --
ham.0 | 2019-07-04 00:03:15.976 | info | cleaned everything up...
ham.0 | 2019-07-04 00:03:15.975 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
ham.0 | 2019-07-04 00:03:15.975 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
ham.0 | 2019-07-04 00:03:15.975 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
ham.0 | 2019-07-04 00:03:15.975 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
ham.0 | 2019-07-04 00:03:15.975 | error | at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2693:25)
ham.0 | 2019-07-04 00:03:15.975 | error | at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:177:27)
ham.0 | 2019-07-04 00:03:15.975 | error | at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:267:39)
ham.0 | 2019-07-04 00:03:15.975 | error | at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:269:14)
ham.0 | 2019-07-04 00:03:15.975 | error | at new Server (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge/lib/server.js:56:38)
ham.0 | 2019-07-04 00:03:15.975 | error | at Server._loadConfig (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge/lib/server.js:230:32)
ham.0 | 2019-07-04 00:03:15.975 | error | TypeError: Cannot read property 'username' of undefined
ham.0 | 2019-07-04 00:03:15.975 | error | uncaught exception: Cannot read property 'username' of undefined
ham.0 | 2019-07-04 00:03:14.621 | info | All Libraries installed/updated
ham.0 | 2019-07-04 00:03:14.620 | info | Install/Update homebridge-config-ui-x

**Comment by Apollon77** [comment]
Dein JSON muss jetzt vollständig sein mit dem "bridge" Teil zu beginn ... am besten kopiere das komplette json wie aus deiner globalen Homebridge Installation

**Comment by Alex18081** [comment]
dafür im Wraper-modus hat homebridge-config-ui-x angelaufen, zeigt auch keine Gärete an, aber menü Geräte ist vorhanden.

**Comment by Alex18081** [comment]
mit das komplette json, funktioniert. aber mit gleiche problem, keine Gärete vorhanden.

**Comment by Alex18081** [comment]
Was ist eigentlich das Lokaler Modus? Muss kein Homebridge vorinstalliert sein wie bei Glabaler Modus?

**Comment by Apollon77** [comment]
Lokaler Modus installiert ein "lokales homebridge" im ioBroker verzeichnis und nutzt das. Damit aber Pakete und Konfig über iobroker aber sonst volle Funktion und verfügbar als Bridge wie bei Global

**Comment by Apollon77** [comment]
AN sich in 1.1.1 erledigt, aber die geräte fehlen ... keine ahnung wie das Plugin intern funktioniert.
e<s wäre super wnen Du dazu ein neues Issue anlegst, aber das wird etwas warten müssen bis ich da tiefer schauen kann
