### ISSUE TITLE
WeMo Plugins don't work

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.ham#3]
There are 2 available versions:
homebridge-platform-wemo
homebridge-wemo

both don't work, with errors like:

> Caught	2018-06-18 18:29:30.358	error	by controller[6]: at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:217:57)
Caught	2018-06-18 18:29:30.358	error	by controller[6]: at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/wrapper-handler.js:90:23)
Caught	2018-06-18 18:29:30.358	error	by controller[6]: at HomebridgeWrapper.init (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/index.js:176:17)
Caught	2018-06-18 18:29:30.358	error	by controller[6]: at Server.run (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:85:36)
Caught	2018-06-18 18:29:30.358	error	by controller[6]: at Server._loadPlatforms (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:314:45)
Caught	2018-06-18 18:29:30.358	error	by controller[6]: at API.platform (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/api.js:122:13)
Caught	2018-06-18 18:29:30.357	error	by controller[6]: Error: The requested platform 'BelkinWeMo' was not registered by any plugin.
Caught	2018-06-18 18:29:30.357	error	by controller[5]: [2018-6-18 18:29:30] ====================
Caught	2018-06-18 18:29:30.357	error	by controller[4]: at Array.forEach (native)
Caught	2018-06-18 18:29:30.357	error	by controller[4]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:147:14)
Caught	2018-06-18 18:29:30.355	error	by controller[4]: at Plugin.load (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/plugin.js:72:22)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at require (internal/module.js:20:19)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at Module.require (module.js:504:17)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at Function.Module._load (/opt/iobroker/node_modules/iobroker.ham/node_modules/mock-require/index.js:29:22)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at Function.Module._load (module.js:445:3)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at tryModuleLoad (module.js:453:12)
Caught	2018-06-18 18:29:30.354	error	by controller[4]: at Module.load (module.js:494:32)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at Object.Module._extensions..js (module.js:586:10)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at Module._compile (module.js:577:32)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-platform-wemo/index.js:26:12)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at new module.exports (/opt/iobroker/node_modules/iobroker.ham/node_modules/wemo-client/index.js:17:22)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at new SsdpClient (/opt/iobroker/node_modules/iobroker.ham/node_modules/wemo-client/node_modules/node-ssdp/lib/client.js:40:8)
Caught	2018-06-18 18:29:30.353	error	by controller[4]: at SsdpClient.SSDP (/opt/iobroker/node_modules/iobroker.ham/node_modules/wemo-client/node_modules/node-ssdp/lib/index.js:81:8)
Caught	2018-06-18 18:29:30.352	error	by controller[4]: at SsdpClient.SSDP._init (/opt/iobroker/node_modules/iobroker.ham/node_modules/wemo-client/node_modules/node-ssdp/lib/index.js:128:54)
Caught	2018-06-18 18:29:30.352	error	by controller[4]: [2018-6-18 18:29:30] TypeError: ip.address is not a function
Caught	2018-06-18 18:29:30.352	error	by controller[3]: [2018-6-18 18:29:30] ERROR LOADING PLUGIN homebridge-platform-wemo:
Caught	2018-06-18 18:29:30.352	error	by controller[2]: [2018-6-18 18:29:30] ====================
Caught	2018-06-18 18:29:30.352	error	by controller[1]: [2018-6-18 18:29:27] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
Caught	2018-06-18 18:29:30.351	error	by controller[0]: [2018-6-18 18:29:27] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0	2018-06-18 18:29:30.321	info	terminating

>

**Comment by Apollon77** [comment]
Please also post the used JSON config

**Comment by Apollon77** [comment]
And please provide FULL debug log (maybe best as log-file attachement) where I can also see that/how npm install worked and such

**Comment by Apollon77** [comment]
Ok forget. Reason found. "ip" is currently mocked away ... i will ad dit as real dep and then you can try gain

**Comment by Apollon77** [comment]
Bitte mit Adapter 0.2.6 neu versuchen.

**Comment by JackWolfskin42** [comment]
Great, works :-)
I can confirm that the wemo plugin is now also supported - tested  with Wemo Insight Switch!
