### ISSUE TITLE
Balboa-Spa

### ISSUE THREAD

**Issue by JPfeiffer66** [ioBroker/ioBroker.ham#323]
Hello!
I try to run the "homebridge-balboa-spa@2.2.6" plugin in the Wrapper-Modus. But it doesn't work.
When I run a seperate Homebridge-Instance this plugin works.
Can you check, what's the issue in the Wrapper-Modus.
Thx

**Comment by JPfeiffer66** [comment]
Hello!
Thank you for your prompt reply.
Now it works! - But I don't know why? ;-)

**Comment by Apollon77** [comment]
lol, these are the bests :-))
