### ISSUE TITLE
homebridge-samsung-tizen not working

### ISSUE THREAD

**Issue by denzel1994** [ioBroker/ioBroker.ham#36]
Ham runs well in local mode. Adding the Homebridge-bridge in HomeKit no problem.
However when I install the Homebridge plugin "homebridge-samsung-tizen" and enter the correct config (this config worked flawlessly on a clean Homebridge install) nothing get's added in objects in ioBroker.

Furthermore, when I try to add the TV to HomeKit and enter the pin code I get following output in the log and the ham-adapter crashes.

<img width="1359" alt="Bildschirmfoto 2019-07-26 um 03 15 22" src="https://user-images.githubusercontent.com/36551243/61918928-9fd20b80-af53-11e9-80ce-9c7428dbf5fe.png">
<img width="560" alt="PNG-Bild" src="https://user-images.githubusercontent.com/36551243/61918931-a5c7ec80-af53-11e9-8c7e-f6b57f5e3d60.png">
<img width="1260" alt="Bildschirmfoto 2019-07-26 um 03 05 00" src="https://user-images.githubusercontent.com/36551243/61918936-a9f40a00-af53-11e9-94f7-b3a84551edf1.png">

Identical setup and config worked on a standalone Homebridge install.

Hope you can help.

**Comment by Apollon77** [comment]
Please delete iobroker-data/ham.0 directory if existient and if there are persisted files in. Does it work after this?

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter
