### ISSUE TITLE
Homebridge stops if i add it to the apple home app

### ISSUE THREAD

**Issue by Kleinstein-github** [ioBroker/ioBroker.ham#37]
here is the error:

host.raspberrypi | 2019-08-04 13:09:00.119 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at endReadableNT (_stream_readable.js:1145:12)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at IncomingMessage.emit (events.js:198:13)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at HAPServer.<anonymous> (/opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at HAPServer._handlePair (/opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at HAPServer._handlePairStepThree (/opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at HAPServer._handlePairStepFour (/opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
host.raspberrypi | 2019-08-04 13:09:00.118 | error | Caught by controller[1]: at HAPServer._handlePairStepFive (/opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/lib/HAPServer.js:457:36)
host.raspberrypi | 2019-08-04 13:09:00.117 | error | Caught by controller[1]: at Function.nacl.sign.detached (/opt/iobroker/node_modules/iobroker.ham/node_modules/tweetnacl/nacl-fast.js:2276:24)
host.raspberrypi | 2019-08-04 13:09:00.117 | error | Caught by controller[1]: at Object.nacl.sign (/opt/iobroker/node_modules/iobroker.ham/node_modules/tweetnacl/nacl-fast.js:2257:11)
host.raspberrypi | 2019-08-04 13:09:00.116 | error | Caught by controller[1]: Error: bad secret key size

**Comment by Apollon77** [comment]
Which mode? Which plugins are configured? Please show configuration. Which nodejs Version?

**Comment by Apollon77** [comment]
And please check the persistence directory (iobroker-data/ham.0/...) and delete it if there is stiff existing. Works it after this?

**Comment by Kleinstein-github** [comment]
I started the hom in the  "Lokaler Modus"
node v10.16.1 
npm v6.10.2

**Comment by Kleinstein-github** [comment]
And please check the persistence directory (iobroker-data/ham.0/...) and delete it if there is stuff existing. Works it after this?


- no nothing happens

**Comment by Apollon77** [comment]
Mithin happens mean same error?

**Comment by Kleinstein-github** [comment]
yes same error

**Comment by Apollon77** [comment]
:-(

**Comment by psanwald** [comment]
I had a very similar problem. It was a misconfiguration of the bridge parameters in config.json. 
Please check, if the username is exactly the mac-address of the system, you are running the homebridge on (You'll find the address in the UI of your router). Also, is the port correct (and not occupied by another application)? Is the pin the one, you are using when connecting from the home app?
In my case the transfer of the system and config file to another system, caused that problem. Of course the other system had a different mac-address...
Example:
`"bridge": {
    "name": "Homebridge",
    "username": "BB:AA:CC:DD:EE:99",
    "port": 34388,
    "pin": "031-45-155"
  }`
So, **in my experience this is NOT a bug**: The error message about wrong pairing parameters was correct in my case. After changing the parameters everything went fine.

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter
