### ISSUE TITLE
Adapter no longer makes updates on Datapoints

### ISSUE THREAD

**Issue by n0bbi** [ioBroker/ioBroker.ham#375]
**Describe the bug**  

Hello,

I use the HAM adapter with Blink-for-home plugin. Recently, I can no longer set states through it. Error messages are not written, in the log is only the following:

<html>
<body>

ham.0 | 2022-06-23 08:28:59.132 | info | updateState Blink-Blink-Daheim.Accessory-Information.Firmware-Revision: value = 3.9.1 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Firmware Revision","unit":""}
-- | -- | -- | --
ham.0 | 2022-06-23 08:28:59.132 | info | updateState Blink-Blink-Daheim.Accessory-Information.Serial-Number: value = 231464127 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Serial Number","unit":""}
ham.0 | 2022-06-23 08:28:59.131 | info | updateState Blink-Blink-Daheim.Accessory-Information.Name: value = Blink Daheim /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2022-06-23 08:28:59.131 | info | updateState Blink-Blink-Daheim.Accessory-Information.Model: value = sm1 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Model","unit":""}
ham.0 | 2022-06-23 08:28:59.131 | info | updateState Blink-Blink-Daheim.Accessory-Information.Manufacturer: value = Blink /common= {"type":"string","read":true,"write":false,"role":"text","name":"Manufacturer","unit":""}
ham.0 | 2022-06-23 08:28:59.130 | info | updateState Blink-Blink-Daheim.Accessory-Information.Identify: value = false /common= {"type":"boolean","read":false,"write":true,"role":"button","name":"Identify","unit":""}
ham.0 | 2022-06-23 08:28:59.129 | info | updateChannel Blink-Blink-Daheim.Accessory-Information: name =
ham.0 | 2022-06-23 08:28:59.128 | info | updateDev Blink-Blink-Daheim: name = Blink Blink Daheim /type= 11
ham.0 | 2022-06-23 08:28:58.654 | info | All Libraries installed/updated
ham.0 | 2022-06-23 08:28:58.653 | info | Install/Update homebridge-blink-for-home@3.9.1
ham.0 | 2022-06-23 08:28:58.653 | info | Install/Update the following Libraries: homebridge-blink-for-home@3.9.1
ham.0 | 2022-06-23 08:28:58.641 | info | starting. Version 4.0.2 in /opt/iobroker/node_modules/iobroker.ham, node: v14.19.3, js-controller: 4.0.23
ham.0 | 2022-06-23 08:28:54.981 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ham.0 | 2022-06-23 08:28:54.980 | info | terminating
ham.0 | 2022-06-23 08:28:54.967 | info | cleaned everything up...
ham.0 | 2022-06-23 08:28:54.967 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>

<html>
<body>

ham.0 | 2022-06-23 08:29:12.308 | info | stateChange ham.0.Blink-Blink-Daheim.Blink-Daheim-Arm.On {"val":true,"ack":false,"ts":1655965752307,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1655965752307}
-- | -- | -- | --
ham.0 | 2022-06-23 08:29:01.083 | info | stateChange ham.0.Blink-Blink-Dachgeschoss.Privacy-Mode.Name {"val":"","ack":true,"ts":1655965740768,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1650436374927}
ham.0 | 2022-06-23 08:29:01.083 | info | stateChange ham.0.Blink-Blink-Dachgeschoss.Privacy-Mode.On {"val":true,"ack":true,"ts":1655965740768,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1655045136147}

</body>
</html>

**Versions:**  
 - Adapter version: v4.0.2
 - JS-Controller version: 4.0.23
 - Node version: 14.19.3
 - Operating system: Ubuntu LXC Container

**Comment by Apollon77** [comment]
What did you change? The adapter do not stop working from a second to the other without any change :-) Please set the loglevel to silly to get more logs and post here

**Comment by RP70DP** [comment]
Use homebridge-blink-for-home@3.7.2

**Comment by Apollon77** [comment]
What you mean?

**Comment by RP70DP** [comment]
Newer version of homebridge-blink-for-home plugin don't work properly.

**Comment by n0bbi** [comment]
I can't get the old version to run either. I think the update was also the crucial change. Currently I assume that it is the Blink module and not the HAM adapter, since I no longer get a 2FA here. Sorry for the inconvenience, it was not obvious to me.

**Comment by Apollon77** [comment]
maybe check the issues in the plugin repo and open a issue there?

**Comment by RP70DP** [comment]
>since I no longer get a 2FA here

This problem was widely discused in the iobroker forum with newer versoin of the plugin. Hence use an older version.

**Comment by Apollon77** [comment]
I meaned in the repo of the homebridge plugin itself ...

**Comment by n0bbi** [comment]
Thank you, the old version is running again. 2FA worked after a few attempts.

**Comment by eklass** [comment]
> ```
> > ham.0 	2022-06-23 08:28:58.653 	info 	Install/Update homebridge-blink-for-home@3.9.1
> > ham.0 	2022-06-23 08:28:58.653 	info 	Install/Update the following Libraries: homebridge-blink-for-home@3.9.1
> ```
> 
> Use homebridge-blink-for-home@3.7.2

It turned out, that the version of the plugin is not the problem. I created an incident for the blink-for-home before (https://github.com/colinbendell/homebridge-blink-for-home/issues/142) but figured out right now that downgrading HAM to 5.3.0 did the trick for me.
Really curios 🤔
