### ISSUE TITLE
v4.0.1 to v4.0.2 ewelink stopped working

### ISSUE THREAD

**Issue by Ivolution-dev** [ioBroker/ioBroker.ham#383]
**Describe the bug**  
The homebrige-ewelink adapter stopped working.

**To Reproduce**  
install v.4.0.1
install homebrige-ewelink
------- should work fine -------
update to v4.0.2
now it should not work

**Versions:**  
 - Adapter version: 4.0.1 and newer
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: linux (raspberry pi iobroker)

**To fix it**  
The homebrige-ewelink adapter worked fine on version ham version v4.0.1 if you update to v4.0.2 the ewelink adapter stopped working. If I downgrade ham to v4.0.1 everything works very well.

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-ewelink/issues/398#issuecomment-1209864546

**Comment by Apollon77** [comment]
Pleas check with ham 5 which is in Beta and short before stable ... But read changelog because it upgrades homebridge!

**Comment by Apollon77** [comment]
Ok, see https://github.com/bwp91/homebridge-ewelink/issues/398#issuecomment-1209969075
