### ISSUE TITLE
xiaomi-fan Modul - Werte werden nicht übernommen

### ISSUE THREAD

**Issue by iPhilBln** [ioBroker/ioBroker.ham#384]
**Describe the bug**  
Die Änderungen in den Datenpunkten werden nicht an das Homebridge Plugin übergeben.

**Screenshots & Logfiles**  
[ham.log](https://github.com/ioBroker/ioBroker.ham/files/9331815/ham.log)

index.js -> Änderung
![Bildschirmfoto 2022-08-13 um 18 26 20](https://user-images.githubusercontent.com/40831653/184502635-6c1457e7-73a3-4cd2-91e8-bf0a4bbe7ba0.png)

**Versions:**  
 - Adapter version: 5.0.2
 - JS-Controller version: 4.0.23
 - Node version: v14.20.0 (auch nach Update auf v16.16.0 keine Änderung)
 - Operating system: Debian Bullseye

**Additional context**  
Hab deine Änderung jetzt in der index.js hinzugefügt, allerdings erscheint sie nicht im log.

**Comment by Apollon77** [comment]
ok, dann hangeln wir uns durch ... geht leider nicht anders ... maximal ne "Anydesk sessioN" wo wir das zusammen bei dir durchprobieren. Ich hab so ein gerät halt nicht

In https://github.com/merdok/homebridge-xiaomi-fan/blob/master/index.js#L574 ist die "get"  FUnktion ... füge da mal analog so eine logInfo zeile ein. Am besten direkt VOR der Callback zeile https://github.com/merdok/homebridge-xiaomi-fan/blob/master/index.js#L580 ...

Weil Daten liesst er ja ... also mal schauen ob er da auch loggt.

Und wenn wir schon dabei sind noch eine bitte bei https://github.com/merdok/homebridge-xiaomi-fan/blob/master/index.js#L940 ... das ist das zyklische Dten neu laden ... Variiere bitte die texte so das man sieht was passiert. Dann schauen wir mal

**Comment by Apollon77** [comment]
PS: And I checked the code: the deep debug flag needs to be in the "devices" level ... so same level as also ip, name and such are defined. So it is "per device" and not general

**Comment by iPhilBln** [comment]
aktuelle index.js:
```
  getRotationSpeed(callback) {
    let fanRotationSpeed = 0;
    if (this.fanDevice && this.fanDevice.isFanConnected()) {
      fanRotationSpeed = this.fanDevice.getRotationSpeed();
      fanRotationSpeed = this.adjustToPercentageRange(fanRotationSpeed);
    }
    this.logInfo(`Try to get Rotationspeed ${fanRotationSpeed}`);
    callback(null, fanRotationSpeed);
  }

  setRotationSpeed(value, callback) {
    this.logInfo(`Try to set Rotationspeed ${value}`);
    if (this.fanDevice && this.fanDevice.isFanConnected()) {
      // use debounce to limit the number of calls when the user slides the rot>
      if (this.rotationSpeedTimeout) clearTimeout(this.rotationSpeedTimeout);
      this.rotationSpeedTimeout = setTimeout(() => this.fanDevice.setRotationSp>
      callback();
    } else {
      callback(this.createError(`cannot set rotation speed`));
    }
  }
...
  updateFanStatus() {
    if (this.fanDevice && this.fanDevice.isFanConnected()) {
      if (this.fanService) {this.fanService.getCharacteristic(Characteristic.Active).updateValue(this.fanDevice.isPowerOn() ? Characteristic.Active.ACTIVE : Characteristic.Active.INACTIVE); this.logInfo(`Aktualisierung des Werts: ${value}`);}

```

Bei dem updateFanStatus() bin ich mir nicht so ganz sicher, was dort hinein soll für value?
Sonst können wir auch gerne ne session die Tage machen. Dann melde dich gerne mal privat.

**Comment by Apollon77** [comment]
> Bei dem updateFanStatus() bin ich mir nicht so ganz sicher, was dort hinein soll für value?

am ende gehts dan nicht um den wert sondern darum ob die logzeile kommt . also kannst da auch das ${value rausnehmen}.

So im Log hier sieht man mindestens einmal das das "get" klappt.

Ok dann jetzt mit vollem log:
* Adapter stoppen
* SSH-Shell öffnen
* `DEBUG=HAP-NodeJS* iob debug ham.0` ausführen
* Das startet den Adapter. Dann bitte wieder aktionen ausführen. Ausgaben bitte posten. 

Privatsession maximal mal tagsüber ... abends ist Urlaub packen und vorschlafen für 10h autofahrt angesagt

**Comment by Apollon77** [comment]
Das ist aber nicht die Ausgabe an der Shell... Bei der variante brauche ich das und nicht das Logfile

**Comment by iPhilBln** [comment]
> Das ist aber nicht die Ausgabe an der Shell... Bei der variante brauche ich das und nicht das Logfile

Ach ok, dachte das wäre identisch im Log . Dann neuer Versuch:
`iobroker@iobroker:~$ DEBUG=HAP-NodeJS* iob debug ham.0 > ham.log` 
liefert das: [ham.log](https://github.com/ioBroker/ioBroker.ham/files/9377215/ham.log)
![Bildschirmfoto 2022-08-18 um 22 01 19](https://user-images.githubusercontent.com/40831653/185484246-6c0618f3-4259-4205-9285-880d36ad9b07.png)

**Comment by Apollon77** [comment]
Ich weiss nicht ob wir so weiterkommen ... ich muss mal überlegen wie ich das ohne solche HW getestet bekomme

**Comment by iPhilBln** [comment]
Ok. Andernfalls habe ich übernächste Woche auch Urlaub. Da könnten wir sonst ggf. sofern du da nicht selbst im Urlaub bist tagsüber ne Session machen.

**Comment by Apollon77** [comment]
ich bin jetzt ab Samstag erstmal 2 Wochen weg :-) Aber auch ne remote session wird auch absolutes try und error und das macht remote einfach keinen spass. ich muss nachdenken

**Comment by iPhilBln** [comment]
Alles klar. Dann wie gesagt erstmal einen schönen Urlaub. :)

**Comment by Apollon77** [comment]
Vorauiss Duplocate von https://github.com/ioBroker/ioBroker.ham/issues/385#issuecomment-1242723427

**Comment by Apollon77** [comment]
Ok, please try newest 5.2.0 Alpha Github version, see https://forum.iobroker.net/topic/57891/test-adapter-ham-5-2-0-github
