### ISSUE TITLE
homebridge-simple-wled keine Objekte im Wrapper-Modus

### ISSUE THREAD

**Issue by teilchenB** [ioBroker/ioBroker.ham#386]
Moin,

ich habe den ham-Adapter im Wrapper-Modus eingerichtet und erhalte z.B. vom NPM-Modul homebridge-airrohr auch Objektdaten. Leider bekomme ich aber keine Daten oder neue Objekte für homebridge-simple-wled.

Die Log-Datei habe ich angehängt:
[iobroker.2022-08-20.log](https://github.com/ioBroker/ioBroker.ham/files/9388608/iobroker.2022-08-20.log)

Vielen Dank

**Comment by Apollon77** [comment]
most likely duplicate of https://github.com/ioBroker/ioBroker.ham/issues/385#issuecomment-1242723427

**Comment by Apollon77** [comment]
Ok, please try newest 5.2.0 Alpha Github version, see https://forum.iobroker.net/topic/57891/test-adapter-ham-5-2-0-github

**Comment by Apollon77** [comment]
5.2.2

**Comment by Apollon77** [comment]
5.2.3
