### ISSUE TITLE
Rights Probleme in "local mode"

### ISSUE THREAD

**Issue by Kleinstein-github** [ioBroker/ioBroker.ham#39]
I use ham 1.1.2

I cant install any plugin

ham.0	2019-08-26 11:07:02.695	info	npm install homebridge-dyson-link --production --prefix "/opt/iobroker/node_modules/iobroker.ham" (System call)
ham.0	2019-08-26 11:07:02.694	error	Cannot install homebridge-dyson-link: 243
ham.0	2019-08-26 11:07:02.652	info	npm ERR! /home/iobroker/.npm/_logs/2019-08-26T10_07_02_609Z-debug.log
ham.0	2019-08-26 11:07:02.652	info	npm ERR! A complete log of this run can be found in:
ham.0	2019-08-26 11:07:02.649	info	
ham.0	2019-08-26 11:07:02.615	info	npm ERR! the command again as root/Administrator (though this is not recommended).
ham.0	2019-08-26 11:07:02.615	info	npm ERR! permissions of the file and its containing directories, or try running
ham.0	2019-08-26 11:07:02.615	info	npm ERR! If you believe this might be a permissions issue, please double-check the
ham.0	2019-08-26 11:07:02.615	info	npm ERR!
ham.0	2019-08-26 11:07:02.615	info	npm ERR! It is likely you do not have the permissions to access this file as the current user
ham.0	2019-08-26 11:07:02.615	info	npm ERR! The operation was rejected by your operating system.
ham.0	2019-08-26 11:07:02.615	info	npm ERR!
ham.0	2019-08-26 11:07:02.615	info	npm ERR! '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist' }
ham.0	2019-08-26 11:07:02.615	info	npm ERR! path:
ham.0	2019-08-26 11:07:02.615	info	npm ERR! syscall: 'access',
ham.0	2019-08-26 11:07:02.615	info	npm ERR! code: 'EACCES',
ham.0	2019-08-26 11:07:02.615	info	npm ERR! errno: -13,
ham.0	2019-08-26 11:07:02.615	info	npm ERR! 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist\'',
ham.0	2019-08-26 11:07:02.615	info	npm ERR! stack:
ham.0	2019-08-26 11:07:02.615	info	npm ERR! { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist']
ham.0	2019-08-26 11:07:02.615	info	npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist'
ham.0	2019-08-26 11:07:02.583	info	npm ERR! syscall access
ham.0	2019-08-26 11:07:02.583	info	npm ERR! errno -13
ham.0	2019-08-26 11:07:02.582	info	EACCES
ham.0	2019-08-26 11:07:02.581	info	npm ERR! code
ham.0	2019-08-26 11:07:02.581	info	ERR! path /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist
ham.0	2019-08-26 11:07:02.580	info	npm
ham.0	2019-08-26 11:07:01.670	info	checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/semver
ham.0	2019-08-26 11:07:01.668	info	WARN
ham.0	2019-08-26 11:07:01.667	info	npm
ham.0	2019-08-26 11:07:01.667	info	npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/q
ham.0	2019-08-26 11:07:01.667	info	WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/mkdirp
ham.0	2019-08-26 11:07:01.666	info	npm
ham.0	2019-08-26 11:07:01.666	info	checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/minimist
ham.0	2019-08-26 11:07:01.664	info	WARN
ham.0	2019-08-26 11:07:01.655	info	npm

**Comment by Apollon77** [comment]
Please use Installation Fixer script to fix rights. Reopen if problem still exists afterwards.
