### ISSUE TITLE
Keine Werte in iobroker von Balboa

### ISSUE THREAD

**Issue by ges7881** [ioBroker/ioBroker.ham#393]
Hallo zusammen,

ich habe folgende Konstellation: Homebridge-Installation auf Synology-NAS. Hier läuft das Balboa Spa Plugin und ich bekomme auch aktuelle Werte zurück --> läuft.
Allerdings wollte ich die Daten im ioBroker, daher habe ich den Ham Adapter Version 5.2.1 installiert und betreibe diese im Local-Mode (Habs auch schon im Wrapper Mode probiert, ändert aber nix.)

To Variablen werden im iobroker angelegt, allerdings werden dies nicht aktualisiert bzw. Werte geschrieben. Die bleiben immer auf 0, egal welcher Mode.

Hier noch meine Konfig:
`{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [],
  "platforms": [
    {
      "name": "Spa",
      "autoCreateAccessories": false,
      "host": "192.168.5.174",
      "devices": [
        {
          "name": "Pump 1",
          "deviceType": "Pump 1"
        },
        {
          "name": "Pump 2",
          "deviceType": "Pump 2"
        },
        {
          "name": "Pump 3",
          "deviceType": "Pump 3"
        },
        {
          "name": "Spa Lights",
          "deviceType": "Lights 1"
        },
        {
          "name": "Spa Temperature",
          "deviceType": "Temperature Sensor"
        },
        {
          "name": "Temperature Control",
          "deviceType": "Thermostat"
        },
        {
          "name": "Flow",
          "deviceType": "Water Flow Problem Sensor"
        }
      ],
      "platform": "Balboa-Spa"
    }
  ]
}`

Könnte mir bitte wer weiterhelfen, was ich hier im Detail falsch mache? Wenn ich auf die Homebridge Installation am Synology verzichten könnte, wer das voll ok.

Danke im Voraus!
Gernot

**Comment by Apollon77** [comment]
please try 5.2.2 just released

**Comment by ges7881** [comment]
Hi Apollon77,

thanks for you comment. I updated the adapter, but it's still the same problem. I get the datapoints with no actual values.

Gernot

**Comment by Apollon77** [comment]
Dann bitte Loglevel einmal auf "silly" und ein log posten vom adapter start.

Und:Was steht beim polling intervaldrin? Es gibt plugins die wertr nicht ativ pushen sondern immer abgefragt werden müssen

**Comment by ges7881** [comment]
[iobroker.current.log.html.pdf](https://github.com/ioBroker/ioBroker.ham/files/9568438/iobroker.current.log.html.pdf)

Intervall steht auf 10s

Beste Grüße

**Comment by Apollon77** [comment]
Bitte nochmal die 5.2.3 versuchen die gerade kommt ... damit bitte ggf neues log wenn Problem noch besteht

**Comment by ges7881** [comment]
Hi,

hab es nun mit der neuesten Version 5.2.4 versucht. Bekomme allerdings immer noch keine Werte.

Hier der Log: [iobroker.current.pdf](https://github.com/ioBroker/ioBroker.ham/files/9574644/iobroker.current.pdf)
und noch jeweils ein Screenshot von homebridge bzw. iobroker:

![Homebridge](https://user-images.githubusercontent.com/106393937/190389936-0779c8ac-9e57-4dd4-81db-7a4d3aa1251b.PNG)
![iobroker](https://user-images.githubusercontent.com/106393937/190389944-eaa1d16f-a68a-49e8-88d9-81c50305b5cc.PNG)


Danke im Voraus und beste Grüße

**Comment by Apollon77** [comment]
Please provide the log as text ... no way to work with that as a pdf

**Comment by Apollon77** [comment]
Also fakt ist das das Plugin wohl erst die geräte ohne Daten anlegt und dann wird "verbunden". Im log sehe ich aber auch 

```
2022-09-15 13:06:17.624 - debug: ham.0 (11133) [15.9.2022, 13:06:17] [Spa] Had error - closing old socket, retrying in 20s
```

Also kann es vllt sein das zwei Systeme gleichzeitig nicht drauf zugreifen können? mal versucht das eine auszuschalten?

Hier müsste man mal das "[Spa]" Logging aus dem system wo es tut vergleichen ... aktuell sehe ich nicht das er daten abgeholt hätte. Auch debug logging von homebridge würde helfen

**Comment by ges7881** [comment]
Sorry, auf das hätte ich auch selber kommen können ;-( 
Das Spa kann anscheinend nur eine Verbindung. Hab die Homebridge-Session deaktiviert und nun bekomme ich Daten. Ob, das Senden auch funktioniert, teste ich am Abend.

Vielen Dank für deine Mühen und deine Hilfe!

BG
Gernot

**Comment by ges7881** [comment]
Hallo,

anbei das log.
Polling interval ist auf 10s

Beste Grüße

Von: Ingo Fischer ***@***.***>
Gesendet: Mittwoch, 14. September 2022 15:38
An: ioBroker/ioBroker.ham ***@***.***>
Cc: ges7881 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.ham] Keine Werte in iobroker von Balboa (Issue #393)


Dann bitte Loglevel einmal auf "silly" und ein log posten vom adapter start.

Und:Was steht beim polling intervaldrin? Es gibt plugins die wertr nicht ativ pushen sondern immer abgefragt werden müssen

**Comment by Apollon77** [comment]
Bitte Logs manuell hochladen. E-Mail Attachements beachtet GitHub nicht

**Comment by Apollon77** [comment]
Weiterhin ... bitte neueste Adapterversion nutzen ...
