### ISSUE TITLE
List of tested plugins

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.ham#4]
Please collect the list of tested plugins like:
homebridge-wemo@1.2.3, Node.js 8.1.2,

And place it in the readme

**Comment by JackWolfskin42** [comment]
Fürs readme...
homebridge-platform-wemo     v1.0.1  @HAM0,26
homebridge-seasons                 v1.0.1   @HAM0.26
homebridge-edomoticz             v2.1.11 @HAM0.26

**Comment by Apollon77** [comment]
I would do it as forum thread better then here/readme .. then link there rom README ... 
Makes sense?

**Comment by Apollon77** [comment]
please collect here: 
https://forum.iobroker.net/viewtopic.php?f=20&t=15021

**Comment by Apollon77** [comment]
Noone reads readme ... and updating it all the time also makes only partial sense for me ... But we can star both if you want

**Comment by GermanBluefox** [comment]
I think, that ham version is not required, but node.js verions

**Comment by GermanBluefox** [comment]
@JackWolfskin42 
Can you add your node.js Version?

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.ham/blob/master/README.md#following-adapters-were-tested-in-default-mode

**Comment by JackWolfskin42** [comment]
Sure, how can I find out which nodejs version is used by ham?

**Comment by GermanBluefox** [comment]
Just write
node -v

вт, 19 июн. 2018 г., 16:16 JackWolfskin42 <notifications@github.com>:

**Comment by JackWolfskin42** [comment]
iobroker:~ $ node -v
v6.13.1

**Comment by Anzic23** [comment]
homebridge-vera@0.8.2, Node.js 8.11.3

**Comment by GermanBluefox** [comment]
homebridge-vera added
