### ISSUE TITLE
Scenes als Objekt

### ISSUE THREAD

**Issue by tommyMX** [ioBroker/ioBroker.ham#459]
Hi,

ist es möglich beim govee plugin (man kann Szenen anlegen) dass man diese auch im Objektbaum ansteuern kann.

<img width="877" alt="Bildschirm­foto 2022-12-23 um 08 45 52" src="https://user-images.githubusercontent.com/36209886/209294915-a7acbec4-a929-4f46-8b95-52e5268d8681.png">
<img width="889" alt="Bildschirm­foto 2022-12-23 um 08 46 04" src="https://user-images.githubusercontent.com/36209886/209294918-c82750c4-6f45-4506-b074-d4fb58fbd3c9.png">

Danke dir

**Comment by Apollon77** [comment]
Siehe FOrum: Alles was das Plugin exposed landet im iobroker als Geräte und states ... wenn es also fehlt ist es Konfigsache des Plugins oder fehlendes Feature des Plugins ...
