### ISSUE TITLE
Add Homebridge Adapter List

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.ham#46]
It would be great to install a plugin on click. To get a list of plugins (JSON), you can use this link.

https://api.npms.io/v2/search?q=keywords:homebridge-plugin&size=100&from=0
https://api.npms.io/v2/search?q=keywords:homebridge-plugin&size=100&from=100
....
https://api.npms.io/v2/search?q=keywords:homebridge-plugin&size=100&from=1700
https://api.npms.io/v2/search?q=keywords:homebridge-plugin&size=100&from=1800

You can also create a Repo-List like in ioBroker with all plugins for it.

> *created by ioBroker.info*

**Comment by ldittmar81** [comment]
Here you can download a JSON List from all Ham plugins.

https://jsfiddle.net/ldittmar/cqpbk7zd/

**Comment by Apollon77** [comment]
Now I only need a Frontend-Developer to adjust the admin pages accordingly ;-)

**Comment by ldittmar81** [comment]
- [ ] List of all plugins
- [ ] Show Readme.md from plugin
- [ ] Create/edit config file for plugin

**Comment by Apollon77** [comment]
will be in 4.0
