### ISSUE TITLE
Homebridge-Tahoma plugin no refresh/change for states

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.ham#47]
Hi,

I have a problem with the control of my blinds.
All objects and states were successfully created after setting up the connection to my SOMFY account.
It is also possible to set the target position manually between 0 and 100% for open and close, this works.

But when I use the original SOMFY app or the SOMFY wall buttons in my house for open and close, then the "current-position" state is not refreshed / changed in ioBroker.
When I restart the adapter it works, the states are changed to the new values for one time.

I tried several values for the "polling intervall" in the adapter configuration (empty, 0 sec, 5 sec, 60 sec, 600 sec) but none of this worked.

nodejs: 10.17.0
npm: 6.12.0
adapter: ham 1.1.2
plugin: homebridge-tahoma

Can you please check this or tell me what I can do / check?

**Comment by Apollon77** [comment]
Can you please set adapter to debug log  (Instances - expert mode - logstufe as column) and post log from init and such an "external" change and a change via iobroker and please note down time-wise when you did what so that I can check log not too blindly ;-)

**Comment by blackeagle998** [comment]
Do you want me to write in english or german, what`s easier for you?

1. Set Polling Intervall to 60 seconds
2. Set ham adapter to debug mode as decribed from you

Testcase:
- blind was "Arbeitszimmer" was closed --> current-position = 0 %
- then I set target-position manually to 25% --> worked, current-position was changed to 25%, blind opened a little bit
- then I opened the blind completely via SOMFY app --> nothing happened with states target-position and current-position, I waited more than two minutes
- then I set target-position manually to 0% --> worked, current-position was changed to 0%, blind was fully closed

Log:
`

ham.0 | 2019-12-05 19:07:36.684 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Position-State
-- | -- | -- | --
ham.0 | 2019-12-05 19:07:36.684 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Position-State {"val":2,"ack":true,"ts":1575569256667,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569256667}
ham.0 | 2019-12-05 19:07:36.683 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Current-Position
ham.0 | 2019-12-05 19:07:36.682 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Current-Position {"val":0,"ack":true,"ts":1575569256667,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569256667}
ham.0 | 2019-12-05 19:07:36.658 | debug | (10097) [2019-12-5 7:07:36 PM] [Connexoon] [Arbeitszimmer] setClosure COMPLETED
ham.0 | 2019-12-05 19:07:20.662 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Position-State
ham.0 | 2019-12-05 19:07:20.661 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Position-State {"val":0,"ack":true,"ts":1575569240658,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569240658}
ham.0 | 2019-12-05 19:07:18.662 | debug | (10097) [2019-12-5 7:07:18 PM] [Connexoon] Listener registered d73eaa79-d9b6-8679-1304-8590e8775d74
ham.0 | 2019-12-05 19:07:18.476 | debug | (10097) [2019-12-5 7:07:18 PM] [Connexoon] [Arbeitszimmer] setClosure[100]
ham.0 | 2019-12-05 19:07:16.486 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Target-Position
ham.0 | 2019-12-05 19:07:16.485 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Target-Position {"val":0,"ack":true,"ts":1575569236479,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569236467}
ham.0 | 2019-12-05 19:07:16.474 | debug | (10097) ack is not set!
ham.0 | 2019-12-05 19:07:16.473 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Target-Position
ham.0 | 2019-12-05 19:07:16.472 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Target-Position {"val":0,"ack":false,"ts":1575569236467,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1575569236467}
ham.0 | 2019-12-05 19:07:11.532 | debug | (10097) system.adapter.admin.0: logging false
ham.0 | 2019-12-05 19:05:47.680 | debug | (10097) system.adapter.admin.0: logging true
ham.0 | 2019-12-05 19:05:46.520 | debug | (10097) system.adapter.admin.0: logging false
ham.0 | 2019-12-05 19:05:03.982 | debug | (10097) system.adapter.admin.0: logging true
ham.0 | 2019-12-05 19:04:22.619 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Position-State
ham.0 | 2019-12-05 19:04:22.619 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Position-State {"val":2,"ack":true,"ts":1575569062612,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569062612}
ham.0 | 2019-12-05 19:04:22.619 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Current-Position
ham.0 | 2019-12-05 19:04:22.618 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Current-Position {"val":26,"ack":true,"ts":1575569062609,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569062609}
ham.0 | 2019-12-05 19:04:22.618 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Current-Position
ham.0 | 2019-12-05 19:04:22.618 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Current-Position {"val":25,"ack":true,"ts":1575569062608,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569062608}
ham.0 | 2019-12-05 19:04:22.600 | debug | (10097) [2019-12-5 7:04:22 PM] [Connexoon] [Arbeitszimmer] setClosure COMPLETED
ham.0 | 2019-12-05 19:04:18.601 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Position-State
ham.0 | 2019-12-05 19:04:18.600 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Position-State {"val":1,"ack":true,"ts":1575569058596,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569058596}
ham.0 | 2019-12-05 19:04:16.183 | debug | (10097) [2019-12-5 7:04:16 PM] [Connexoon] Listener registered d73be1ab-d9b6-8679-1304-8590ebf76764
ham.0 | 2019-12-05 19:04:16.010 | debug | (10097) [2019-12-5 7:04:16 PM] [Connexoon] [Arbeitszimmer] setClosure[75]
ham.0 | 2019-12-05 19:04:14.013 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Target-Position
ham.0 | 2019-12-05 19:04:14.012 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Target-Position {"val":25,"ack":true,"ts":1575569054010,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569054003}
ham.0 | 2019-12-05 19:04:14.007 | debug | (10097) ack is not set!
ham.0 | 2019-12-05 19:04:14.006 | debug | (10097) lookup id: Arbeitszimmer.Arbeitszimmer.Target-Position
ham.0 | 2019-12-05 19:04:14.006 | info | (10097) stateChange ham.0.Arbeitszimmer.Arbeitszimmer.Target-Position {"val":25,"ack":false,"ts":1575569054003,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1575569054003}
ham.0 | 2019-12-05 19:04:07.601 | debug | (10097) system.adapter.admin.0: logging false
ham.0 | 2019-12-05 19:03:54.790 | debug | (10097) lookup id: Entryway.0000007F.Name
ham.0 | 2019-12-05 19:03:54.789 | info | (10097) stateChange ham.0.Entryway.0000007F.Name {"val":"","ack":true,"ts":1575569034674,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.753 | debug | (10097) lookup id: Entryway.0000007F.Carbon-Monoxide-Peak-Level
ham.0 | 2019-12-05 19:03:54.753 | info | (10097) stateChange ham.0.Entryway.0000007F.Carbon-Monoxide-Peak-Level {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.751 | debug | (10097) lookup id: Entryway.0000007F.Carbon-Monoxide-Level
ham.0 | 2019-12-05 19:03:54.751 | info | (10097) stateChange ham.0.Entryway.0000007F.Carbon-Monoxide-Level {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.727 | debug | (10097) lookup id: Entryway.0000007F.Status-Tampered
ham.0 | 2019-12-05 19:03:54.726 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Tampered {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.725 | debug | (10097) lookup id: Entryway.0000007F.Status-Low-Battery
ham.0 | 2019-12-05 19:03:54.725 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Low-Battery {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.723 | debug | (10097) lookup id: Entryway.0000007F.Status-Fault
ham.0 | 2019-12-05 19:03:54.723 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Fault {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.721 | debug | (10097) lookup id: Entryway.0000007F.Status-Active
ham.0 | 2019-12-05 19:03:54.719 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Active {"val":false,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.718 | debug | (10097) lookup id: Entryway.0000007F.Manual-Test-Active
ham.0 | 2019-12-05 19:03:54.718 | info | (10097) stateChange ham.0.Entryway.0000007F.Manual-Test-Active {"val":false,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.717 | debug | (10097) lookup id: Entryway.0000007F.Status-Active
ham.0 | 2019-12-05 19:03:54.716 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Active {"val":true,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569034657}
ham.0 | 2019-12-05 19:03:54.715 | debug | (10097) lookup id: Entryway.0000007F.Status-Low-Battery
ham.0 | 2019-12-05 19:03:54.715 | info | (10097) stateChange ham.0.Entryway.0000007F.Status-Low-Battery {"val":0,"ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775537}
ham.0 | 2019-12-05 19:03:54.714 | debug | (10097) lookup id: Entryway.0000007F.Name
ham.0 | 2019-12-05 19:03:54.713 | info | (10097) stateChange ham.0.Entryway.0000007F.Name {"val":"Entryway Carbon Monoxide","ack":true,"ts":1575569034657,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569034657}
ham.0 | 2019-12-05 19:03:54.711 | debug | (10097) lookup id: Entryway.0000007F.Carbon-Monoxide-Detected
ham.0 | 2019-12-05 19:03:54.711 | info | (10097) stateChange ham.0.Entryway.0000007F.Carbon-Monoxide-Detected {"val":0,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.710 | debug | (10097) lookup id: Entryway.00000087.Name
ham.0 | 2019-12-05 19:03:54.710 | info | (10097) stateChange ham.0.Entryway.00000087.Name {"val":"","ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.709 | debug | (10097) lookup id: Entryway.00000087.Status-Low-Battery
ham.0 | 2019-12-05 19:03:54.708 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Low-Battery {"val":0,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.707 | debug | (10097) lookup id: Entryway.00000087.Status-Tampered
ham.0 | 2019-12-05 19:03:54.707 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Tampered {"val":0,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.706 | debug | (10097) lookup id: Entryway.00000087.Status-Fault
ham.0 | 2019-12-05 19:03:54.706 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Fault {"val":0,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.705 | debug | (10097) lookup id: Entryway.00000087.Status-Active
ham.0 | 2019-12-05 19:03:54.705 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Active {"val":false,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.704 | debug | (10097) lookup id: Entryway.00000087.Manual-Test-Active
ham.0 | 2019-12-05 19:03:54.704 | info | (10097) stateChange ham.0.Entryway.00000087.Manual-Test-Active {"val":false,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.702 | debug | (10097) lookup id: Entryway.00000087.Status-Active
ham.0 | 2019-12-05 19:03:54.702 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Active {"val":true,"ack":true,"ts":1575569034656,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569034656}
ham.0 | 2019-12-05 19:03:54.702 | debug | (10097) lookup id: Entryway.00000087.Status-Low-Battery
ham.0 | 2019-12-05 19:03:54.701 | info | (10097) stateChange ham.0.Entryway.00000087.Status-Low-Battery {"val":0,"ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775536}
ham.0 | 2019-12-05 19:03:54.700 | debug | (10097) lookup id: Entryway.00000087.Name
ham.0 | 2019-12-05 19:03:54.700 | info | (10097) stateChange ham.0.Entryway.00000087.Name {"val":"Entryway Smoke","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569034655}
ham.0 | 2019-12-05 19:03:54.699 | debug | (10097) lookup id: Entryway.00000087.Smoke-Detected
ham.0 | 2019-12-05 19:03:54.699 | info | (10097) stateChange ham.0.Entryway.00000087.Smoke-Detected {"val":0,"ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775535}
ham.0 | 2019-12-05 19:03:54.698 | debug | (10097) lookup id: Entryway.Accessory-Information.Accessory-Flags
ham.0 | 2019-12-05 19:03:54.698 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775535}
ham.0 | 2019-12-05 19:03:54.697 | debug | (10097) lookup id: Entryway.Accessory-Information.Hardware-Revision
ham.0 | 2019-12-05 19:03:54.697 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775535}
ham.0 | 2019-12-05 19:03:54.695 | debug | (10097) lookup id: Entryway.Accessory-Information.Firmware-Revision
ham.0 | 2019-12-05 19:03:54.695 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Firmware-Revision {"val":"3.1.4rc3","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":15755337
ham.0 | 2019-12-05 19:03:54.695 | debug | (10097) lookup id: Entryway.Accessory-Information.Serial-Number
ham.0 | 2019-12-05 19:03:54.694 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Serial-Number {"val":"06AA01AC331701QN","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575
ham.0 | 2019-12-05 19:03:54.694 | debug | (10097) lookup id: Entryway.Accessory-Information.Name
ham.0 | 2019-12-05 19:03:54.694 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Name {"val":"Entryway","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775535}
ham.0 | 2019-12-05 19:03:54.693 | debug | (10097) lookup id: Entryway.Accessory-Information.Model
ham.0 | 2019-12-05 19:03:54.693 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Model {"val":"Nest Protect","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775535}
ham.0 | 2019-12-05 19:03:54.691 | debug | (10097) lookup id: Entryway.Accessory-Information.Manufacturer
ham.0 | 2019-12-05 19:03:54.691 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Manufacturer {"val":"Nest","ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775534}
ham.0 | 2019-12-05 19:03:54.690 | debug | (10097) lookup id: Entryway.Accessory-Information.Identify
ham.0 | 2019-12-05 19:03:54.690 | info | (10097) stateChange ham.0.Entryway.Accessory-Information.Identify {"val":false,"ack":true,"ts":1575569034655,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775533}
ham.0 | 2019-12-05 19:03:54.686 | debug | (10097) lookup id: Home/Away.Home-Occupied.Name
ham.0 | 2019-12-05 19:03:54.686 | info | (10097) stateChange ham.0.Home/Away.Home-Occupied.Name {"val":"","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775530}
ham.0 | 2019-12-05 19:03:54.686 | debug | (10097) lookup id: Home/Away.Home-Occupied.On
ham.0 | 2019-12-05 19:03:54.683 | info | (10097) stateChange ham.0.Home/Away.Home-Occupied.On {"val":true,"ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575544751261}
ham.0 | 2019-12-05 19:03:54.683 | debug | (10097) lookup id: Home/Away.Home-Occupied.Name
ham.0 | 2019-12-05 19:03:54.682 | info | (10097) stateChange ham.0.Home/Away.Home-Occupied.Name {"val":"Home Occupied","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575569034654}
ham.0 | 2019-12-05 19:03:54.682 | debug | (10097) lookup id: Home/Away.Accessory-Information.Accessory-Flags
ham.0 | 2019-12-05 19:03:54.682 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775529}
ham.0 | 2019-12-05 19:03:54.682 | debug | (10097) lookup id: Home/Away.Accessory-Information.Hardware-Revision
ham.0 | 2019-12-05 19:03:54.682 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775529}
ham.0 | 2019-12-05 19:03:54.681 | debug | (10097) lookup id: Home/Away.Accessory-Information.Firmware-Revision
ham.0 | 2019-12-05 19:03:54.681 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Firmware-Revision {"val":"3.1.4rc3","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533
ham.0 | 2019-12-05 19:03:54.681 | debug | (10097) lookup id: Home/Away.Accessory-Information.Serial-Number
ham.0 | 2019-12-05 19:03:54.681 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Serial-Number {"val":"06AA01AC331701QN","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":157
ham.0 | 2019-12-05 19:03:54.680 | debug | (10097) lookup id: Home/Away.Accessory-Information.Name
ham.0 | 2019-12-05 19:03:54.680 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Name {"val":"Home/Away","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775529}
ham.0 | 2019-12-05 19:03:54.680 | debug | (10097) lookup id: Home/Away.Accessory-Information.Model
ham.0 | 2019-12-05 19:03:54.680 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Model {"val":"Nest Home/Away Sensor","ack":true,"ts":1575569034654,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":157553
ham.0 | 2019-12-05 19:03:54.679 | debug | (10097) lookup id: Home/Away.Accessory-Information.Manufacturer
ham.0 | 2019-12-05 19:03:54.679 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Manufacturer {"val":"Nest","ack":true,"ts":1575569034653,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775529}
ham.0 | 2019-12-05 19:03:54.679 | debug | (10097) lookup id: Home/Away.Accessory-Information.Identify
ham.0 | 2019-12-05 19:03:54.678 | info | (10097) stateChange ham.0.Home/Away.Accessory-Information.Identify {"val":false,"ack":true,"ts":1575569034653,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1575533775529}
ham.0 | 2019-12-05 19:03:54.621 | debug | (10097) Homebridge Wrapper Bridge publish {"username":"FF:FF:FF:FF:FF:FF","port":0,"pincode":"0","category":2}

`

**Comment by Apollon77** [comment]
Can you try to set "refreshPeriod" in the plugin config to a lower value in your config ... default value according to plugin github page is 600s (=10min) ...  or wait that time

Alternatively you can also set the "characteristic Polling Interval" in the HAM admin to a value different then 0 (0 means no polling).

Basically Homebridge loads the values when you open the page in the Home app and so fetches the current values. If you would use two devices and use Somfy app one one and have the home app open on the page with the data on the second and then change in somfy app ... also home app would not update the values. So it seems to you need to poll in case of this "Protocol".

Is that working then?

**Comment by blackeagle998** [comment]
I set "refreshPeriod" to 5 seconds, that worked.
Thank you very much!!!

Unbelievable that I did not see this option yesterday... :-)

**Comment by Apollon77** [comment]
But think about if 5s is really best ... it is much radio-traffic. ...
