### ISSUE TITLE
Global Mode Logfile

### ISSUE THREAD

**Issue by Huelsi** [ioBroker/ioBroker.ham#52]
My adapter is running in global mode and everything seems to be running smooth since a few months. But there seems to be a glitch with the loging. For me it looks like that the levels info and debug are switched. For example every status change is listed in the info mode but the general info about the plugins that are loaded are only displayed in debug mode.
Is there a way to change this behavior?
For better understanding I uploaded a screenshot. Grey debug message with date and time in my understanding should be the output for the info level. Black info messages and grey info messages without date and time should be the output for debug level.
![Bildschirmfoto 2020-02-10 um 17 16 01](https://user-images.githubusercontent.com/51848903/74168526-2fa68100-4c2a-11ea-9e6b-32e23415e18d.jpg)

**Comment by Apollon77** [comment]
This is intended. Logging from homebridge itself is debug. Logging thatchers from the iobroker adapter part is Info in this case. And this makes sense because homebridge is „under the hood“ in our case ...

**Comment by Apollon77** [comment]
Why you would see that changed?

**Comment by Huelsi** [comment]
Hmm okay got it. There are two reasons. First is that with the info level activated the log is full of homebridge state changes for every polling to the homebridge devices e.g. hue lamps and homematic thermostats. Therefore I had to change the ham logging to warn. Another thing is that whenever I want to connect a new device and see if something went wrong I have to switch to debug level and see if I can find the device between the 600+ lines after starting the adapter.

**Comment by Huelsi** [comment]
> This is intended. Logging from homebridge itself is debug. Logging thatchers from the iobroker adapter part is Info in this case. And this makes sense because homebridge is „under the hood“ in our case ...

Ist there a way to start homebridge "under the hood" without debug logging? This qould probably solve it for me too. As I guess without debug logging I cant see the state changes and info logging should display the messages that I expect to see?

**Comment by Apollon77** [comment]
When you just set loglevel to "info" then the "debug" should not appear in the logs and on e the info logs should appear

**Comment by Huelsi** [comment]
When I set the log level to info in iobroker only the info messages appear but the info messages contain the statechange messages that fill up the logfile by hundreds of lines in a matter of minutes. When I run homebridge outside of iobroker the statechange messages are only output to the log file when debug logging is activated. Do you get what I mean? (no english nativ here, I can also try to describe it in german if necessary)

**Comment by Apollon77** [comment]
I can change these stateChanges to debug also ... but basically then "infgo" will not provide much more ... so setting loglebel to warn would be completely valid ... why you do not like it? :-)

**Comment by Huelsi** [comment]
Basically info then would be empty :) But when homebridge (standalone) is set to normal logging the info [date/time] [PlugIn] "information" e.g. [2/10/2020, 17:15:21] [Roborock] INF ...  as you can see on the screenshot is output to logfile. My understanding would be, that this is output to info loglevel and the StateChanges are output on debug loglevel.

**Comment by Apollon77** [comment]
No, in fact it is the following way:
* All log from homebridge itself is defined as "debug"
* Logs from the adapter is set by the adapter to debig or info
