### ISSUE TITLE
Plugin Update homebridge-fibaro-hc2

### ISSUE THREAD

**Issue by Flopsi75** [ioBroker/ioBroker.ham#54]
Hello
how can update the plugin? I use the homebridge-fibaro-hc2 plugin. How can I find out which version of the plugin I currently have?

Thank you for your support

**Comment by Apollon77** [comment]
The plugin is installed in the node_modules directory inside node_modules/iobroker.ham ... so you can check there. I will add a "update npm modules" flag

**Comment by Apollon77** [comment]
BTW: just set the "update libraries flag in Admin and all npm modules that exists will be updated on next start
