### ISSUE TITLE
iobroker.ham funktioniert nicht mehr mit homebridge 1.0.x

### ISSUE THREAD

**Issue by fugazzy** [ioBroker/ioBroker.ham#58]
iobroker.ham funktioniert nicht mehr mit homebridge 1.0.x

**Comment by denzel1994** [comment]
Indeed no functionality with 1.0.x

**Comment by Apollon77** [comment]
Jupp. Bitte downgraden. Die 1.0 ist wie die Versionsnummer sagt „breaking“ und da hat sich sehr viel geändert. Muss mal schauen was geht überhaupt.

**Comment by Mr-REM-Esq** [comment]
> Jupp. Bitte downgraden. Die 1.0 ist wie die Versionsnummer sagt „breaking“ und da hat sich sehr viel geändert. Muss mal schauen was geht überhaupt.

Do I need to downgrade to 0.4.5? How should I do it?

**Comment by Apollon77** [comment]
If you have the adaoter working again then yes you should downgrade. Downgrade the same way as you updated but with @0.4.5 or such

**Comment by Apollon77** [comment]
Somehow you updated homebridge ... it was not via the adapter

**Comment by Mr-REM-Esq** [comment]
> Somehow you updated homebridge ... it was not via the adapter

Yes, I upgraded it too. Do I need downgrade adapter or homebridge?

**Comment by Apollon77** [comment]
homebridge is the reason not the adapter

**Comment by Mr-REM-Esq** [comment]
OK. f I stay the current version of the adapter and downgrade the homebridge it will be enough?

**Comment by Apollon77** [comment]
should be

**Comment by Mr-REM-Esq** [comment]
Which version of hombridge is right for me?

**Comment by Apollon77** [comment]
which one you had befopre you upgraded homebride? I don't know ... it needs to be <1.0

**Comment by Mr-REM-Esq** [comment]
I am updated on every new version

**Comment by Mr-REM-Esq** [comment]
sudo npm install -g -unsafe-perm homebridge@0.4.53 -g

Is it right command?

**Comment by fugazzy** [comment]
Is there any chance to get this fixed quite soon? Otherwise it would start to separate homebridge and iobroker again.
I activated the Iobroker-Homematic-Adapter already, because I needed to geht the information about tilted windows to HomeKit (virtual switch in homebridge and script in iobroker)

**Comment by Apollon77** [comment]
Quite soon ... hm ... let me think ... homebridge 1.1.0 is based on a new hap library version and both projects where converted to typescript and so i consider them as a rewrite. The ham adapter is doing quite some interception magic and overwrites methods from the original classes. 

You are welcome to get familiar with all of this and provide needed PRs and code changes. Then it will be faster.

If you can not then I‘m really sorry that you need to wait till I find time analyzing this. 

The solution to get it working again for now is to head back to homebridge <1.0 ... or what’s the exact reason to be on 1.x?

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter

**Comment by entavio** [comment]
i have updated to v2.0 and the adapter gets green again with the plugin https://github.com/merdok/homebridge-xiaomi-fan/issues/17

but the problem is i don't get any data set points for mapping to yahka

**Comment by Apollon77** [comment]
As said: Please set iobroker adapter logging to debug (instances - exper mode - column loglevel) and then get the full log from adapter start from the logfile on disk (NOT via admin web ui!!) (/opt/iobroker/log/...) and post here
