### ISSUE TITLE
Suddenly there were errors in the log

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.ham#59]
ham.0 | 2020-05-08 18:07:59.579 | info | (5008) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
ham.0 | 2020-05-08 18:07:59.577 | info | (5008) terminating
ham.0 | 2020-05-08 18:07:59.548 | info | (5008) cleaned everything up...
ham.0 | 2020-05-08 18:07:59.546 | error | at checkLocalMode (/opt/iobroker/node_modules/iobroker.ham/main.js:397:25)
ham.0 | 2020-05-08 18:07:59.546 | error | at checkLocalMode (/opt/iobroker/node_modules/iobroker.ham/main.js:203:13)
ham.0 | 2020-05-08 18:07:59.546 | error | at installAllLibraries (/opt/iobroker/node_modules/iobroker.ham/main.js:378:21)
ham.0 | 2020-05-08 18:07:59.546 | error | at installAllLibraries (/opt/iobroker/node_modules/iobroker.ham/main.js:217:39)
ham.0 | 2020-05-08 18:07:59.546 | error | at Object.init (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:88:12)
ham.0 | 2020-05-08 18:07:59.546 | error | at require (internal/modules/cjs/helpers.js:25:18)
ham.0 | 2020-05-08 18:07:59.546 | error | at Module.require (internal/modules/cjs/loader.js:692:17)
ham.0 | 2020-05-08 18:07:59.546 | error | at Function.Module._load (/opt/iobroker/node_modules/iobroker.ham/node_modules/mock-require/index.js:30:22)
ham.0 | 2020-05-08 18:07:59.546 | error | at Function.Module._load (internal/modules/cjs/loader.js:562:25)
ham.0 | 2020-05-08 18:07:59.546 | error | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
ham.0 | 2020-05-08 18:07:59.546 | error | (5008) Error: Cannot find module '/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once'
ham.0 | 2020-05-08 18:07:59.545 | error | (5008) uncaught exception: Cannot find module '/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once'
ham.0 | 2020-05-08 18:07:58.884 | info | (5008) No additional Libraries to install ...
ham.0 | 2020-05-08 18:07:58.850 | info | (5008) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.ham, node: v10.20.1, js-controller: 3.0.20
host.iobroker | 2020-05-08 18:07:56.850 | info | instance system.adapter.ham.0 started with pid 5008

How to solve this problem?

**Comment by Apollon77** [comment]
Yes, you upgraded to homebridge 1.x? Right? Not supported right now

**Comment by Apollon77** [comment]
duplicate to #58

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter
