### ISSUE TITLE
Ham adapter is not displayed, no interface / Ham Adaper wird nicht angezeigt, keine Oberfläche

### ISSUE THREAD

**Issue by sansonifabio** [ioBroker/ioBroker.ham#612]
The Ham Adapter interface is no longer displayed since the last update of ioBroker.

Die Oberfläche des Ham Adapters wird seit den letzten Update von ioBroker nicht mehr angezeigt.

Grüße
Fabio

![homebridge](https://github.com/ioBroker/ioBroker.ham/assets/88761140/0d14e192-5472-4727-a6fb-d08e2e149bae)

JS: 5.0.12
Admin:  6.10.1
Node.js: 18.17.1

**Comment by sansonifabio** [comment]
Also ich habe weiterhin diese Problem.

**Comment by Apollon77** [comment]
Gibt es Fehler in der Brower konsole? Sonst bitte einfach die normale Admin Konfig nutzen

**Comment by sansonifabio** [comment]
Nein kein Fehler im Log. Mal ist die Seite  da mal wieder nicht. Vielleicht ein Lade Problem des Frame?

**Comment by Apollon77** [comment]
Nicht im Log - in Der Fehlerkonsole vom Browser!

**Comment by sansonifabio** [comment]
Nein ich sehe da Nix. Das komische ist das die Seite mal da ist mal nicht. Ich beobachte das mal bis zum Wochenende weiter. Wenn's dann gut läuft mach ich hier zu. Evtl. dauert es zu lange bis der Server antwortet. Komisch nur das mir dieses Verhalten erst aufgefallen ist als ich den Iobroker auf die Version 5.0.12 gehoben hab. Kann auch Zufall sein. Herzliche Grüße Fabio

**Comment by sansonifabio** [comment]
Hallo @Apollon77 

ich mach jetzt zu, der Fehler trat bis gerade nicht mehr auf. Evtl. hing es da am Server von wo geladen wird.

Grüße
Fabio
