### ISSUE TITLE
planned to go to on HomeBridge Server version 1.x?

### ISSUE THREAD

**Issue by tobsta** [ioBroker/ioBroker.ham#62]
I am trying to get somehow arlo working on iobroker. I found out about homebridge-arlo module (not sure if this is working anyway). Actually it looks like this module need a higher version of underlying HomeBridge Server. Are there any plans to update to a server of 1.x version? 
  
`Error: Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-arlo requires a HomeBridge version of >=1.0.0 which does not satisfy the current HomeBridge version of 0.4.50. You may need to upgrade your installation of HomeBridge.`

thanks for you great work!!!

**Comment by Apollon77** [comment]
duplicate #58

**Comment by Apollon77** [comment]
yes there are planse ... I "just" need to find time or someone else

**Comment by tobsta** [comment]
oups.... sorry for duplicate - havent read the other issue to the end.

thanks for the answer - and, be sure, i know very well about that "finding time" issue. So it was just a gentle question. I am already very impressed about your work and your time you invest! Thanks a lot!

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter

**Comment by tobsta** [comment]
thanks a lot! 
updated in iobroker via GIT - this went to 3.0 - now there are error messages in log but i think origin of these is homebridge-arlo module. I'm running HAM in wrapper mode - maybe i have to move to global or local mode, but i have no clue which mode and how to.

`(31403) uncaught exception: Cannot read property 'videoProcessor' of undefined
error: host.iobroker Caught by controller[0]: [8/8/2020, 9:36:25 AM] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.`

`error: host.iobroker Caught by controller[1]: [8/8/2020, 9:36:25 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-arlo' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-arlo'.`

`error: host.iobroker Caught by controller[2]: [8/8/2020, 9:36:25 AM] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.`

or do you see anything i screwed up here? this "already loaded" sounds strange for me.

**Comment by Apollon77** [comment]
The already loaded is ok and just reason that it seems that the npm module is installed twice somewhere. 

Do you have more info on the error or is this really anything?

**Comment by Apollon77** [comment]
@tobsta Is your arlo homebridge config correct? There seems to be missing a parameter or config completely missing https://github.com/EpicKris/homebridge-arlo/blob/master/ArloCameraSource.js#L26

**Comment by tobsta** [comment]
@Apollon77 thanks for spending time for investigating my issue.
this is was happens in the log when starting the ham adapter:
`
ham.0 | 2020-08-09 19:05:00.920 | info | (19122) terminating
ham.0 | 2020-08-09 19:05:00.913 | warn | (19122) Exception: TypeError: Cannot read property 'videoProcessor' of undefined
ham.0 | 2020-08-09 19:05:00.908 | info | (19122) cleaned everything up...
ham.0 | 2020-08-09 19:05:00.907 | error | (19122) TypeError: Cannot read property 'videoProcessor' of undefined at new ArloCameraSource (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-arlo/ArloCameraSource.js:26:38) a
ham.0 | 2020-08-09 19:05:00.904 | error | (19122) uncaught exception: Cannot read property 'videoProcessor' of undefined
`
my config is as follows:
`
"platforms": [
    {
      "platform": "Arlo",
      "name": "Arlo",
      "email": "xxx",
      "password": "***",
      "interval": 6000
    }
  ]
`
i installed ffmpeg (i think this is default) on the rasp but i guess this was not enough.
Sorry for my noobiness

**Comment by Apollon77** [comment]
This is an iddue in the plugin - they do not really check for parameter existance :( YOu should open an issue there.,

Work around should be to add a "streaming: {}" as part of the platform config. like here in https://github.com/EpicKris/homebridge-arlo/wiki/Manual-Setup#sample-configuration-with-optional-parameters ... can be empty, but that "streaming" object needs to be there

**Comment by tobsta** [comment]
ah okay! Great! now everything starts without any issue or error in the logs - but without any created objects as well (like it was when i used other plugins like e.g. tado in ham) but i think this is an plugin or DAU issue as well
