### ISSUE TITLE
HAM Adapter erweitern, dass auch iobroker Datenpunkt in HomeKit sichtbar sind

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.ham#63]
Es wäre toll, wenn der Adapter auch der exportieren von iobroker Datenpunkten ermöglichen würde.

Das Yakha Adapter kann das zwar, aber die Bedienung ist eine Zumutung und das Restore von einem Backup funktioniert auch nicht vernünftig.

**Comment by Apollon77** [comment]
Neee, das ist nicht der Purpose des Adapters. Möglich wäre yahka oder ein homebridge iobroker Plugin

**Comment by Apollon77** [comment]
PS: Im Notfall muss man yahka halt fixen. Aber der Adapter kann das nicht liefern
