### ISSUE TITLE
Installation/update iobroker.ham failed 

### ISSUE THREAD

**Issue by entavio** [ioBroker/ioBroker.ham#64]
**Describe the bug**  
installation in iobroker via git failed 

**Screenshots & Logfiles**  

Install https://github.com/ioBroker/ioBroker.ham/tarball/master
NPM version: 6.14.5
npm install https://github.com/ioBroker/ioBroker.ham/tarball/master --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@iobroker%2fadapter-core - Not found
npm ERR! 404 npm ERR! 404  '@iobroker/adapter-core@^2.3.1' is not in the npm registry.npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Versions:**  
 - Adapter version: 3.0
 - JS-Controller version: 2.2.9
 - Node version: 12.18.2.
 - Operating system: linux (Diskstation)

**Comment by Apollon77** [comment]
try again, there was an outage of npm!

**Comment by entavio** [comment]
perfect thx

**Comment by Apollon77** [comment]
BTW: npm issues still ongoing :-( so might still be broken
