### ISSUE TITLE
any chance to reduce the log entries

### ISSUE THREAD

**Issue by hanwel** [ioBroker/ioBroker.ham#65]
Thanks for the work!
Great adapter.
But: I have connected a dyson pure cool and this device is logging thousands (really!) of densitiy changes in the ioBroker log. So it would be great to have an option to reduce this or - better - to switch off.
Thanks, Hanno.

**Comment by Apollon77** [comment]
Simply set the loglevel of the instance to warn. ;-)

Instances - expert mode -column loglevel

**Comment by hanwel** [comment]
Wow, so easy ;)
Thank you, made my day.
