### ISSUE TITLE
Missing Fibaro devices in the object list

### ISSUE THREAD

**Issue by fjosepose** [ioBroker/ioBroker.ham#69]
I have installed the "Homebridge accessories manager" in the ioBroker, and connected it to my FIbaro HC2-system. When the two systems are synced an object list is produced. This object list is missing several devices from my HC2-system and there seems not to be a system of which devices that are missing, however the missing devices are consistent.

**Expected behavior**  
I would guess that the object list in the ioBroker should mirror all devices in the HC2.

**Versions:**  
 - Adapter version: 1.1.2
 - JS-Controller version: 2.3.0.0
 - Node version: 10.17.0
 - Operating system: Windows10

**Additional context**

**Comment by Apollon77** [comment]
Please check older issues ... there were already two of them whwre always the homebridge plugin simply did not returned them ... so then adapter can not do anything and the plugin needs to fix it ... please enable debug log and check if the devices are returned

**Comment by fjosepose** [comment]
Hi
Yes, I’ll have a look/search for these issues. I noticed one similarity in respect to virtual devices. If a virtual device do not have a button and labels only it is not imported. If the virtual device have a button the device is imported, but the labels are excluded...

Anyway, I’ll have a look at it tomorrow, and hopefully there is a sollution for it in the old issues!

**Comment by fjosepose** [comment]
Hi
I have had a look at the two old issues, and I cannot find any actions there I should do, except from updating the system as I have done this morning.

There are still missing devices, both physical devices like my ventilation unit where the "fan device" is missing. 

On virtual devices it seems like all devices without a button is missing, but this might be intentional? However, being able to read virtual device labels into ioBroker is of great interest.

I have deleted all entries in the object list, and re-synced the system. The same devices are still missing, and they are noe present in the log either. To me there seems to be no trace of these devices in the "ioBroker environment"

Please advice.

**Comment by fjosepose** [comment]
Hello again
I have done a fresh win10 installation, as well as a new ioBroker installation + updates. I still have missing devices, both real and virtual from the Fibaro HC2. 

I see in the Object list that I currently have Objects=3563 and States=2986, and I read in the forum that these(?) number have previously bees an issue, but some limit was once again increased.

I think the ioBroker(with the Visualization adapter) have the functions I need to build a custom dashboard, but I need to figure this issue out. At this point I´m now a little clueless.

**Comment by Apollon77** [comment]
You can always verify if the devices missed by the adapter or the homebridge module itself with installing homebridge and inserting the module there. If then the same devices are missing please check with the plugin developer why they are missing. The adapter can only "see" what is exposed by the plugin!

If in homebridge all devices are present then I need a full debug log from ham adapter starte with same config as in homebridge

**Comment by fjosepose** [comment]
Hi. I have notified the plug-in developers, it just took me some time to get familiar to the platform and git. So let´s see what they say.
