### ISSUE TITLE
States request in global-mode

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.ham#7]
When we use global-homebridge-mode it would be great to have an option to initiate ham device status update from iobroker.

**Comment by Apollon77** [comment]
Please test 1.0.0 from GitHub!

**Comment by algar42** [comment]
Works fine from first look. Thank you!!
PS: Please add unit (seconds) to Poll option :)

**Comment by Apollon77** [comment]
Should be there ... directly after the field ...not? hm ...

**Comment by algar42** [comment]
No, can't see.. hmmm..

![image](https://user-images.githubusercontent.com/40002726/50086233-698a1c00-020d-11e9-8400-acf295f9b95c.png)

**Comment by Apollon77** [comment]
grr ... moved to next line ... :-(
need to check how i need to set unit for materialize stuff :-(

**Comment by algar42** [comment]
Can't we just add to \DIV text in index_m.html? 
![image](https://user-images.githubusercontent.com/40002726/50089036-be319500-0215-11e9-977a-5b80f3ac4332.png)

**Comment by Apollon77** [comment]
also an idea
 :-)

**Comment by algar42** [comment]
Actually, I did not realize that this was a unit:
![image](https://user-images.githubusercontent.com/40002726/50089256-57f94200-0216-11e9-8c27-74fa60e6e90e.png)
Probably if we will use (sec) or (seconds) instead of just (s) it will be clearer :)

**Comment by algar42** [comment]
this looks better :)

![image](https://user-images.githubusercontent.com/40002726/50089363-b6bebb80-0216-11e9-977b-cd2b680163de.png)

**Comment by Apollon77** [comment]
will release it later as now on Github (only one time "secs" ;-) )

**Comment by Apollon77** [comment]
1.0.0 released to npm. Install as latest
