### ISSUE TITLE
Adapter geht nach Verbindungsaufbau nach kurzer Zeit vom Satus von Grün auf Rot 

### ISSUE THREAD

**Issue by Paule84** [ioBroker/ioBroker.ham#70]
Nabend ich habe folgendes Problem, der Adapter verbindet kurz und dann bekomme ich per Log den unten aufgeführten Fehler und anschließend geht der Adapter wieder vom Staus auf Inaktiv. Die Objekte sind angelegt, 

![image](https://user-images.githubusercontent.com/33681571/93930322-78283000-fd1d-11ea-8349-8149093dfb82.png)

Hab ich eventuell ein Berechtigungsproblem ?

/var/lib/homebridge/
![image](https://user-images.githubusercontent.com/33681571/93930582-e53bc580-fd1d-11ea-971d-6a914efe3b80.png)

/usr/lib/node_modules/homebridge/
![image](https://user-images.githubusercontent.com/33681571/93930743-1fa56280-fd1e-11ea-85b5-48fed4992b54.png)

Log:
host.PISERVER | 2020-09-22 21:39:28.606 | error | instance system.adapter.ham.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
-- | -- | -- | --
host.PISERVER | 2020-09-22 21:39:28.605 | error | Caught by controller[5]: }
host.PISERVER | 2020-09-22 21:39:28.605 | error | Caught by controller[5]: path: '/var/lib/homebridge/accessories/cachedAccessories'
host.PISERVER | 2020-09-22 21:39:28.605 | error | Caught by controller[5]: code: 'EACCES',
host.PISERVER | 2020-09-22 21:39:28.605 | error | Caught by controller[5]: syscall: 'open',
host.PISERVER | 2020-09-22 21:39:28.605 | error | Caught by controller[5]: errno: -13,
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at process._fatalException (internal/process/execution.js:165:25) {
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at process.emit (events.js:327:22)
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at process.<anonymous> (/opt/iobroker/node_modules/iobroker.ham/main.js:46:48)
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at Object.end (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:272:16)
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at Server.teardown (/usr/lib/node_modules/homebridge/lib/server.js:469:14)
host.PISERVER | 2020-09-22 21:39:28.604 | error | Caught by controller[5]: at Server.saveCachedPlatformAccessoriesOnDisk (/usr/lib/node_modules/homebridge/lib/server.js:213:30)
host.PISERVER | 2020-09-22 21:39:28.603 | error | Caught by controller[5]: at LocalStorage.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
host.PISERVER | 2020-09-22 21:39:28.603 | error | Caught by controller[5]: at LocalStorage.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:16)
host.PISERVER | 2020-09-22 21:39:28.603 | error | Caught by controller[5]: at Object.writeFileSync (fs.js:1362:35)
host.PISERVER | 2020-09-22 21:39:28.603 | error | Caught by controller[5]: at Object.openSync (fs.js:462:3)
host.PISERVER | 2020-09-22 21:39:28.603 | error | Caught by controller[5]: Error: EACCES: permission denied, open '/var/lib/homebridge/accessories/cachedAccessories'
host.PISERVER | 2020-09-22 21:39:28.602 | error | Caught by controller[5]: ^
host.PISERVER | 2020-09-22 21:39:28.602 | error | Caught by controller[5]: throw e;
host.PISERVER | 2020-09-22 21:39:28.602 | error | Caught by controller[5]: /usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:480
host.PISERVER | 2020-09-22 21:39:28.602 | error | Caught by controller[4]: [0;37m[2020-9-22 21:39:28] [0;36m[Config] [0;31mEnding process now.
host.PISERVER | 2020-09-22 21:39:28.602 | error | Caught by controller[4]: [0;37m[2020-9-22 21:39:28] [0;36m[Config] [0;31mPlease stop the other service or change the port you have assigned to homebridge-config-ui-x.
host.PISERVER | 2020-09-22 21:39:28.601 | error | Caught by controller[4]: [0;37m[2020-9-22 21:39:28] [0;36m[Config] [0;31mAnother process or service on this host is using port 8581.
host.PISERVER | 2020-09-22 21:39:28.601 | error | Caught by controller[3]: [0;37m[2020-9-22 21:39:28] [0;36m[Config] [0;31mError: listen EADDRINUSE: address already in use :::8581
host.PISERVER | 2020-09-22 21:39:28.601 | error | Caught by controller[2]: [0;37m[2020-9-22 21:39:27] [0;36m[Config] [0;33mHomebridge Config UI X v4.27.1 is listening on :: port 8581
host.PISERVER | 2020-09-22 21:39:28.601 | error | Caught by controller[1]: [2020-9-22 21:39:20] Plugin /usr/lib/node_modules/homebridge/ does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
host.PISERVER | 2020-09-22 21:39:28.600 | error | Caught by controller[0]: [2020-9-22 21:39:20] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.

**Comment by Apollon77** [comment]
Caught by controller[5]: Error: EACCES: permission denied, open '/var/lib/homebridge/accessories/cachedAccessories'

Heisst der iobroker user darf an den genannten (globalen) Pfad nicht schreiben. Das musst Du fixen

**Comment by jannnfe** [comment]
Und wie?

**Comment by Apollon77** [comment]
DFa ich dein system nicht kenne und nur annehmen kann das /var/lib/homebridge root oder einem homebridge user läuft, aber ioBroker üblicherweise unter "iobroker"  musst Du die Verzeichnisrechte anpassen. Mehr support für sowas gern im ioBroker Forum

**Comment by jannnfe** [comment]
Ja das stimmt, ich habe Homebridge nach [dieser](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian) Anleitung installiert. Demnach läuft mein Homebridge unter dem Benutzer homebridge und liegt im Pfad: /var/lib/homebridge/ 
Mein ioBroker läuft unter dem Benutzer iobroker. Ich habe noch nie etwas im ioBroker Forum geschrieben. Wie soll ich jetzt nun vorgehen, also wo soll ich die Frage nochmal stellen im Forum? :)

**Comment by Apollon77** [comment]
SUch im Forum doch ambesten nach Honebridget oder HAM.

Sorry aber bevor ich mit meinem virtelwissen hier falsche Linux Rechtetips gebe, gebe ich lieber keine :-)

**Comment by jannnfe** [comment]
Hab's denke ich gefunden: https://forum.iobroker.net/topic/35794/iobroker-ham-3-0-1-global-modus-startet-nicht/19
Aber so wie ich lese, funktioniert der globale Modus nur wenn der ioBroker Adapter ham das global installierte Homebridge startet. Verstehe ich nicht wieso das so ist. So kommt der Adapter leider nicht für mich in Frage. :/

**Comment by Apollon77** [comment]
Der Adapter hat drei Modi und ja der globale funktioniert so
