### ISSUE TITLE
Upgrade to homebridge 1.3.x as soon as version gets stable

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.ham#73]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by worf0r** [comment]
Hi all,

1.3.0 is stable now. I use global mode. Objects in IoBroker not being upgraded. Did downgrade to 1.2.5 now.

Marc

**Comment by Apollon77** [comment]
Honestly ... when I see the issues and aready a 1.3.1 then i would not really consider it s "stable" :-) SO I will wait for another 1-2 weeks at least

**Comment by worf0r** [comment]
1.3.2 is out now. Does it make sense to test it? Or rather wait again?

**Comment by Apollon77** [comment]
... and they work on 1.3.3 already ;-)) But all good. I spent the whole day yesterday to get it working with 1.3.

You can try "adapter preview 4.0.0" from GitHub if you like. (please make sure to have git installed). Note: Child bridges will NOT work in global/local mode! I still think how it could work ...

**Comment by Apollon77** [comment]
Github updated to 1.3.3 ...
@worf0r Any feedback from a test from you?

**Comment by worf0r** [comment]
Hi Apollon!

Yes, I installed 1.3.3 in global mode und 4.0.0 from github. It is running and looks good so far.

Except of these messages:

ham.0 | 2021-03-11 14:11:14.395 | warn | (5796) Error while getting current value: -70405
-- | -- | -- | --
ham.0 | 2021-03-11 14:11:14.395 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:13.922 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:11:12.853 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:11.735 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:11.735 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:11.335 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:11:10.351 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:08.868 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:08.867 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:08.412 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:11:07.454 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:07.454 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:07.454 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:05.523 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:11:04.668 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:03.271 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:03.271 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:02.776 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:11:01.915 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:01.914 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:11:01.914 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:59.938 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:10:58.865 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:57.537 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:57.536 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:57.166 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:10:56.199 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:55.002 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:55.002 | warn | (5796) Error while getting current value: -70405
ham.0 | 2021-03-11 14:10:54.660 | warn | (5796) Error while getting current value: -70402
ham.0 | 2021-03-11 14:10:53.731 | warn | (5796) Error while getting current value: -70405

**Comment by Apollon77** [comment]
If you want to know more on that error please enablde debug log ... thne we should see better when it happens

**Comment by worf0r** [comment]
ham.0 | 2021-03-11 22:33:23.317 | debug | (14507) [2021-3-11 22:33:23] [HomeMatic CCU] [Core] will cache ccu response to /var/lib/homebridge/ccu.json
-- | -- | -- | --
ham.0 | 2021-03-11 22:33:23.257 | debug | (14507) [2021-3-11 22:33:23] [HomeMatic CCU] [Core] NPM 0.2.226 vs Local 0.2.226
ham.0 | 2021-03-11 22:33:23.018 | debug | (14507) lookup id: HP-Vik-&-Marc-Printing.HP-Vik-&-Marc-Printing.Contact-Sensor-State
ham.0 | 2021-03-11 22:33:23.018 | info | (14507) stateChange ham.0.HP-Vik-&-Marc-Printing.HP-Vik-&-Marc-Printing.Contact-Sensor-State {"val":0,"ack":true,"ts":1615498398754,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":
ham.0 | 2021-03-11 22:33:22.817 | warn | (14507) Error while getting current value: -70402
ham.0 | 2021-03-11 22:33:22.748 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:22.407 | warn | (14507) Error while getting current value: -70402
ham.0 | 2021-03-11 22:33:22.292 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:22.213 | warn | (14507) Error while getting current value: -70402
ham.0 | 2021-03-11 22:33:22.072 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:22.072 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:22.072 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:21.804 | warn | (14507) Error while getting current value: -70402
ham.0 | 2021-03-11 22:33:21.632 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:21.620 | warn | (14507) Error while getting current value: -70405
ham.0 | 2021-03-11 22:33:21.031 | debug | (14507) [2021-3-11 22:33:21] Homebridge v1.3.3 (Homebridge 8950) is running on port 51048.
ham.0 | 2021-03-11 22:33:21.030 | debug | (14507) Starting to advertise 'Homebridge 8950 C1A5' using ciao backend!
ham.0 | 2021-03-11 22:33:21.029 | debug | (14507)
ham.0 | 2021-03-11 22:33:21.029 | debug | (14507) └────────────┘
ham.0 | 2021-03-11 22:33:21.029 | debug | (14507) │ 355-84-441 │
ham.0 | 2021-03-11 22:33:21.029 | debug | (14507) ┌────────────┐
ham.0 | 2021-03-11 22:33:21.028 | debug | (14507)
ham.0 | 2021-03-11 22:33:21.028 | debug | (14507) Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
ham.0 | 2021-03-11 22:33:21.027 | debug | (14507) [47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m [0m[47m
ham.0 | 2021-03-11 22:33:20.958 | debug | (14507) Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
ham.0 | 2021-03-11 22:33:20.957 | debug | (14507) X-HM://002424989HJJG
ham.0 | 2021-03-11 22:33:20.957 | debug | (14507) Setup Payload:
ham.0 | 2021-03-11 22:33:20.955 | debug | (14507) Preparing Advertiser for 'Homebridge 8950 C1A5' using ciao backend!

Not sure if it is really helpful. Will kepp an eye on it. In general, everything seems to be working fine. Great Job, Apollon! Thanks for all the work!

**Comment by Apollon77** [comment]
This comes as error fgrom the homebridge plugin and the number seems to be an error code or such ... check with the lugin please
