### ISSUE TITLE
HAM crashes in global mode, trying to load plugins in wrapper mode

### ISSUE THREAD

**Issue by Tyraenor** [ioBroker/ioBroker.ham#76]
**Describe the bug**  
HAM should start the existing global instance of Homebridge, but still tries to load plugins in wrapper mode and crashes then with the following errors:

> Caught by controller[1]: [10/02/2021, 11:29:58] Plugin /usr/local/lib/node_modules/homebridge/ does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
> Caught by controller[0]: [10/02/2021, 11:30:31] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.

**To Reproduce**  
Configure in global mode and start the instance

**Expected behavior**  
Instance to start and Homebridge to start

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 3.0.2
 - JS-Controller version: 3.1.6
 - Node version: 14.15.4
 - Operating system: Raspbian v1.0.15

**Comment by Apollon77** [comment]
Please show the config and full start debug log

**Comment by Tyraenor** [comment]
```
host.homebridge | 2021-02-10 12:00:03.756 | info | instance system.adapter.ham.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
host.homebridge | 2021-02-10 12:00:03.756 | error | Caught by controller[3]: [10/02/2021, 12:00:02] Plugin /usr/local/lib/node_modules/homebridge/ does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
host.homebridge | 2021-02-10 12:00:03.756 | error | Caught by controller[2]: [10/02/2021, 12:00:02] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-harmony' since we already loaded the same plugin from '/opt/iobroker/node_modu
host.homebridge | 2021-02-10 12:00:03.755 | error | Caught by controller[1]: [10/02/2021, 12:00:02] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
host.homebridge | 2021-02-10 12:00:03.755 | error | Caught by controller[0]: [10/02/2021, 12:00:02] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0 | 2021-02-10 12:00:03.220 | info | (21802) Terminated (NO_ERROR): Without reason
ham.0 | 2021-02-10 12:00:03.219 | info | (21802) terminating
ham.0 | 2021-02-10 12:00:03.192 | info | (21802) cleaned everything up...
ham.0 | 2021-02-10 12:00:03.190 | error | (21802) Error: EACCES: permission denied, open '/var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf' at Object.openSync (fs.js:476:3) at Object.writeFileSync (fs.js:1467:35) at Lo
ham.0 | 2021-02-10 12:00:03.189 | error | (21802) unhandled promise rejection: EACCES: permission denied, open '/var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf'
ham.0 | 2021-02-10 12:00:03.188 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ham.0 | 2021-02-10 12:00:01.194 | info | (21802) No additional Libraries to install ...
ham.0 | 2021-02-10 12:00:01.160 | info | (21802) starting. Version 3.0.2 in /opt/iobroker/node_modules/iobroker.ham, node: v14.15.4, js-controller: 3.1.6
host.homebridge | 2021-02-10 11:59:59.822 | info | instance system.adapter.ham.0 started with pid 21802
host.homebridge | 2021-02-10 11:59:59.793 | info | "system.adapter.ham.0" enabled


```

![ham_config](https://user-images.githubusercontent.com/35043931/107501476-b8d2f980-6b97-11eb-9fe5-0d23f1817b69.png)

**Comment by Tyraenor** [comment]
> ```
> host.homebridge | 2021-02-10 12:00:03.756 | info | instance system.adapter.ham.0 terminated with code 0 (NO_ERROR)
> -- | -- | -- | --
> host.homebridge | 2021-02-10 12:00:03.756 | error | Caught by controller[3]: [10/02/2021, 12:00:02] Plugin /usr/local/lib/node_modules/homebridge/ does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
> host.homebridge | 2021-02-10 12:00:03.756 | error | Caught by controller[2]: [10/02/2021, 12:00:02] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-harmony' since we already loaded the same plugin from '/opt/iobroker/node_modu
> host.homebridge | 2021-02-10 12:00:03.755 | error | Caught by controller[1]: [10/02/2021, 12:00:02] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
> host.homebridge | 2021-02-10 12:00:03.755 | error | Caught by controller[0]: [10/02/2021, 12:00:02] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
> ham.0 | 2021-02-10 12:00:03.220 | info | (21802) Terminated (NO_ERROR): Without reason
> ham.0 | 2021-02-10 12:00:03.219 | info | (21802) terminating
> ham.0 | 2021-02-10 12:00:03.192 | info | (21802) cleaned everything up...
> ham.0 | 2021-02-10 12:00:03.190 | error | (21802) Error: EACCES: permission denied, open '/var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf' at Object.openSync (fs.js:476:3) at Object.writeFileSync (fs.js:1467:35) at Lo
> ham.0 | 2021-02-10 12:00:03.189 | error | (21802) unhandled promise rejection: EACCES: permission denied, open '/var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf'
> ham.0 | 2021-02-10 12:00:03.188 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> ham.0 | 2021-02-10 12:00:01.194 | info | (21802) No additional Libraries to install ...
> ham.0 | 2021-02-10 12:00:01.160 | info | (21802) starting. Version 3.0.2 in /opt/iobroker/node_modules/iobroker.ham, node: v14.15.4, js-controller: 3.1.6
> host.homebridge | 2021-02-10 11:59:59.822 | info | instance system.adapter.ham.0 started with pid 21802
> host.homebridge | 2021-02-10 11:59:59.793 | info | "system.adapter.ham.0" enabled
> ```
> 
> ![ham_config](https://user-images.githubusercontent.com/35043931/107501476-b8d2f980-6b97-11eb-9fe5-0d23f1817b69.png)

And the file /var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf does not exist, I do not know, why it tries to access it...

**Comment by Apollon77** [comment]
YOu have an permission topic!

iobroker runs as "iobroker "user ... and I expect that the directory /var/lib/homebridge/persist/ belongs to root ... you need to make sure that iobroker user can access that directly in order for global mode to work!

**Comment by Tyraenor** [comment]
> YOu have an permission topic!
> 
> iobroker runs as "iobroker "user ... and I expect that the directory /var/lib/homebridge/persist/ belongs to root ... you need to make sure that iobroker user can access that directly in order for global mode to work!

Thank you for the reply.

I do not understand why it tries to access a file, which definitely does not exist.
Maybe I will give it a try, but for now I switched to wrapper mode, and it works fine for the stuff I need.

If I tried it and it fails anyway I will let you know. But in the meantime you can close this here.

**Comment by Apollon77** [comment]
it is easy: The adapter starts homebridge wirth the global config and global location ... but not as root ... and your global homebridge uses this persistence directory ... and thats why iobroker user needs to have persmissions here.

**Comment by Tyraenor** [comment]
Yes, I know this. BUT!!! The file it tries to open does not exist. So why it tries to access a file which is not existing?

**Comment by Apollon77** [comment]
> ham.0 | 2021-02-10 12:00:03.190 | error | (21802) Error: EACCES: permission denied, open '/var/lib/homebridge/persist/0b5915069b97869e1c3a51e3e655ceaf' at Object.openSync (fs.js:476:3) at Object.writeFileSync (fs.js:1467:35) at Lo

it seems that write seems to open tehe file to find out if it exists
