### ISSUE TITLE
No states from homebridge in global mode

### ISSUE THREAD

**Issue by Tyraenor** [ioBroker/ioBroker.ham#78]
**Describe the bug**  
The adapter loads fine now in global mode, but there is no ham.0 in objects, so no states are available.

**To Reproduce**  
Start the adapter

**Expected behavior**  
ham.0 in objects with states from homebridge

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 3.0.2
 - JS-Controller version: 3.2.16
 - Node version: v12.20.2
 - Operating system: Raspbian Buster

**Comment by Apollon77** [comment]
Which homebridge version is installed? Please provide debug log

**Comment by worf0r** [comment]
I would guess it is 1.3.0 stable. I have the same problem with 1.3.0 stable. See issue about 1.3.0 stable.

**Comment by Apollon77** [comment]
see my comment, a 1.3.1 is in work and still many problem reports in isues on 1.3.x ... so I will wait a bit before update

**Comment by Apollon77** [comment]
duplicate to https://github.com/ioBroker/ioBroker.ham/issues/73
