### ISSUE TITLE
Homebridge-Tab: When installing tuya-web plugin end in "no data" state

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.ham#85]
I installed the tuya-web plugin.

After that only "no data" is shown and this in konsole

And I see

![Bildschirmfoto 2021-03-07 um 15 13 32](https://user-images.githubusercontent.com/11976694/110242739-b0cc6680-7f57-11eb-930d-678b5b8a2bb8.png)

**Comment by Apollon77** [comment]
PS: I tried to install tuya-web plugin ... after removing anything of that plugin it works again

**Comment by UncleSamSwiss** [comment]
Can you provide the exact list of plugins from the adapter config "Main Settings" page? There are many "tuya-web" plugins.

**Comment by Apollon77** [comment]
<img width="1009" alt="Bildschirmfoto 2021-03-18 um 22 24 07" src="https://user-images.githubusercontent.com/11976694/111699649-b6b82680-8838-11eb-97ae-23edf4901533.png">

as soon as I add that tuya thing the tab is broken, also in current version

**Comment by UncleSamSwiss** [comment]
This bug is fixed in the PR, but unfortunately the schema form doesn't work for this plugin, so the user has to fall back to the JSON editor.
