### ISSUE TITLE
GlobalModus issue

### ISSUE THREAD

**Issue by OliTheo** [ioBroker/ioBroker.ham#9]
I have homebridge and iobroker running on my raspberrypi.
seetings for Global Moduls are '/usr/local/lib/node_modules/homebridge/ '  and  '/root/.homebridge/'

it is connecting and receiving also the information from the homebridge but it also restartet due several problems:

host.raspberrypi | 2018-10-18 21:25:05.521 | info | Restart adapter system.adapter.ham.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2018-10-18 21:25:05.521 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
host.raspberrypi | 2018-10-18 21:25:05.521 | error | Caught  by controller[0]:     at initAdapter  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)  code: 'MODULE_NOT_FOUND' }
host.raspberrypi | 2018-10-18 21:25:05.520 | error | Caught by controller[0]:     at Adapter.emit (events.js:208:7)
host.raspberrypi | 2018-10-18 21:25:05.520 | error | Caught by controller[0]:     at emitNone (events.js:106:13)
host.raspberrypi | 2018-10-18 21:25:05.520 | error | Caught by controller[0]:     at Adapter.main (/opt/iobroker/node_modules/iobroker.ham/main.js:198:31)
host.raspberrypi | 2018-10-18 21:25:05.520 | error | Caught by controller[0]:     at Object.init (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:52:33)
host.raspberrypi | 2018-10-18 21:25:05.519 | error | Caught by controller[0]:     at module.exports (/opt/iobroker/node_modules/iobroker.ham/lib/mapper.js:15:20)
host.raspberrypi | 2018-10-18 21:25:05.519 | error | Caught by controller[0]:     at require (internal/module.js:11:18)
host.raspberrypi | 2018-10-18 21:25:05.519 | error | Caught by controller[0]:     at Module.require (module.js:597:17)
host.raspberrypi | 2018-10-18 21:25:05.518 | error | Caught by controller[0]:     at Function.Module._load (module.js:475:25)
host.raspberrypi | 2018-10-18 21:25:05.518 | error | Caught by controller[0]:     at Function.Module._resolveFilename (module.js:548:15)
host.raspberrypi | 2018-10-18 21:25:05.517 | error | Caught by controller[0]: { Error: Cannot find module 'homebridge-plugin-wrapper'
host.raspberrypi | 2018-10-18 21:25:02.805 | info | instance system.adapter.ham.0 started with pid 26134
host.raspberrypi | 2018-10-18 21:24:32.779 | info | Restart adapter system.adapter.ham.0 because enabled

Error2

ham.0 | 2018-10-18 21:24:32.693 | info | terminating
-- | -- | -- | --
ham.0 | 2018-10-18 21:24:32.241 | warn | Exception: Error: Cannot find module 'homebridge-plugin-wrapper'
ham.0 | 2018-10-18 21:24:32.238 | info | cleaned everything up...
ham.0 | 2018-10-18 21:24:32.236 | error | at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
ham.0 | 2018-10-18 21:24:32.236 | error | at Adapter.emit (events.js:208:7)
ham.0 | 2018-10-18 21:24:32.236 | error | at emitNone (events.js:106:13)
ham.0 | 2018-10-18 21:24:32.236 | error | at Adapter.main (/opt/iobroker/node_modules/iobroker.ham/main.js:198:31)
ham.0 | 2018-10-18 21:24:32.236 | error | at Object.init (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:52:33)
ham.0 | 2018-10-18 21:24:32.236 | error | at module.exports (/opt/iobroker/node_modules/iobroker.ham/lib/mapper.js:15:20)
ham.0 | 2018-10-18 21:24:32.236 | error | at require (internal/module.js:11:18)
ham.0 | 2018-10-18 21:24:32.236 | error | at Module.require (module.js:597:17)
ham.0 | 2018-10-18 21:24:32.236 | error | at Function.Module._load (module.js:475:25)
ham.0 | 2018-10-18 21:24:32.236 | error | at Function.Module._resolveFilename (module.js:548:15)
ham.0 | 2018-10-18 21:24:32.236 | error | Error: Cannot find module 'homebridge-plugin-wrapper'
ham.0 | 2018-10-18 21:24:32.235 | error | uncaught exception: Cannot find module 'homebridge-plugin-wrapper'
ham.0 | 2018-10-18 21:24:32.165 | info | starting. Version 0.4.5 in /opt/iobroker/node_modules/iobroker.ham, node: v8.12.0
ham.0 | 2018-10-18 20:59:54.749 | error | adapter disabled
ham.0 | 2018-10-18 20:59:22.531 | info | terminating
ham.0 | 2018-10-18 20:59:22.062 | warn | Exception: Error: Cannot find module 'homebridge-plugin-wrapper'
ham.0 | 2018-10-18 20:59:22.060 | info | cleaned everything up..

I am not sure how to add this homebridge-plugin-wrapper, and even if it was installed it was not configured correct.  any help would be great.

Thanks
Oliver

@gaudes do you have any idea? @nicoh88

**Comment by Apollon77** [comment]
This normally is a dependency of the ioBroker adapter. Please maybe reinstall the adapter.

**Comment by Apollon77** [comment]
No answer since October ...
