### ISSUE TITLE
Installationsproblem bei Node14 - "exit25"

### ISSUE THREAD

**Issue by Jenne20** [ioBroker/ioBroker.ham#91]
Moin,

bei Installation unter Node 14 kommt folgender Fehler, dem ich zwar "lesen" aber nicht verstehen kann:

info it worked if it ends with ok

warn npm npm does not support Node.js v14.16.0

warn npm You should probably upgrade to a newer version of node as we

warn npm can't make any promises that npm will work with this version.

warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.

warn npm You can find the latest version at https://nodejs.org/

verbose cli [
6 verbose cli   '/usr/bin/node',
6 verbose cli   '/usr/local/bin/npm',
6 verbose cli   'install',
6 verbose cli   'iobroker.ham@3.0.2',
6 verbose cli   '--loglevel',
6 verbose cli   'error',
6 verbose cli   '--prefix',
6 verbose cli   '/opt/iobroker'
6 verbose cli ]

info using npm@6.4.1

info using node@v14.16.0

verbose npm-session 381e9366485f30a7

silly install loadCurrentTree

silly install readLocalPackageData

verbose stack TypeError: cb.apply is not a function

verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18

verbose stack     at FSReqCallback.oncomplete (fs.js:184:5)

verbose cwd /opt/iobroker

verbose Linux 5.4.72-v7l+

verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "iobroker.ham@3.0.2" "--loglevel" "error" "--prefix" "/opt/iobroker"
verbose node v14.16.0

verbose npm  v6.4.1

error cb.apply is not a function

verbose exit [ 1, true ]

==> Welchen Ansatz muss ich wählen? NPM neu installieren?

**Comment by Apollon77** [comment]
Das ist kein Adapter issue ... Bitte am besten im Forum nach Support wegen npm Fragen

**Comment by Jenne20** [comment]
OK - sorry, bin recht neu was dies angeht ;-)

**Comment by Apollon77** [comment]
kein Problem, ich denke nur das die User im Forum die besser halfen können als ich in so einem "Komischen" Fall :-)
